### ISSUE TITLE
Pre-trained imagenet models

### ISSUE THREAD

**Issue by alexgkendall** [mapillary/inplace_abn#1]
Awesome work, this is really nice for training big segmentation models!

Any chance you could please share pre-trained imagenet weights for your models?

**Comment by pkontschieder** [comment]
@alexgkendall All ImageNet trained models from our paper have been added for download. Have fun!

**Comment by mingminzhen** [comment]
Why can not i open the downloaded model? Could you help recheck them? Or you can provide the .pth file directly.

**Comment by rotabulo** [comment]
@mingminzhen We do provide the .pth.tar file for each model. You can download it by following the md5-link in the table containing the pre-trained models  (last column).

**Comment by mingminzhen** [comment]
In fact, i have downloaded the models. But I can not extract the .pth file correctly. It seems the .tar file is corrupted.

**Comment by rotabulo** [comment]
@mingminzhen the model file is not supposed to be extracted. You should load it from python using `torch.load`.
