### ISSUE TITLE
About pre-trained model

### ISSUE THREAD

**Issue by asfavdfqefc** [mapillary/inplace_abn#100]
If I use a backbond(such as resnet101) which use this inplace abn, I must use the pre-trained model' weight that you give?

**Comment by rotabulo** [comment]
@asfavdfqefc no, you can use inplace ABN in any architecture, you just need to properly replace BN+Activation with Inplace ABN. We provide a pre-trained resnet101 to show that we can reproduce the scores of the original models and allow to use it directly via our repository.

**Comment by asfavdfqefc** [comment]
ok  I see, Thank you very much
