### ISSUE TITLE
Command '['ninja', '-v']' returned non-zero exit status 1

### ISSUE THREAD

**Issue by zsp1993** [mapillary/inplace_abn#104]
Traceback (most recent call last):
  File "/home/peng/anaconda2/envs/python36/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 576, in _build_extension_module
    ['ninja', '-v'], stderr=subprocess.STDOUT, cwd=build_directory)
  File "/home/peng/anaconda2/envs/python36/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/home/peng/anaconda2/envs/python36/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 35, in <module>
    from network import Network
  File "/home/peng/pytorch-seg-new/experiments/SimpleMerge_NYU/network.py", line 20, in <module>
    import resnet101_dilation
  File "../../basemodel/resnet101_dilation.py", line 18, in <module>
    from LibInplaceABN.modules import InPlaceABNSync, ABN, GlobalAvgPool2d
  File "../../lib/LibInplaceABN/modules/__init__.py", line 1, in <module>
    from .bn import ABN, InPlaceABN, InPlaceABNSync
  File "../../lib/LibInplaceABN/modules/bn.py", line 10, in <module>
    from .functions import *
  File "../../lib/LibInplaceABN/modules/functions.py", line 18, in <module>
    extra_cuda_cflags=["--expt-extended-lambda"])
  File "/home/peng/anaconda2/envs/python36/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 501, in load
    _build_extension_module(name, build_directory)
  File "/home/peng/anaconda2/envs/python36/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 582, in _build_extension_module
    name, error.output.decode()))
RuntimeError: Error building extension 'inplace_abn': [1/5] /usr/local/cuda-9.1/bin/bin/nvcc -DTORCH_EXTENSION_NAME=inplace_abn -I/home/peng/anaconda2/envs/python36/lib/python3.6/site-packages/torch/lib/include -I/home/peng/anaconda2/envs/python36/lib/python3.6/site-packages/torch/lib/include/TH -I/home/peng/anaconda2/envs/python36/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/cuda-9.1/bin/include -I/home/peng/anaconda2/envs/python36/include/python3.6m --compiler-options '-fPIC' --expt-extended-lambda -std=c++11 -c /home/peng/pytorch-seg-new/lib/LibInplaceABN/modules/src/inplace_abn_cuda.cu -o inplace_abn_cuda.cuda.o
FAILED: inplace_abn_cuda.cuda.o 
/usr/local/cuda-9.1/bin/bin/nvcc -DTORCH_EXTENSION_NAME=inplace_abn -I/home/peng/anaconda2/envs/python36/lib/python3.6/site-packages/torch/lib/include -I/home/peng/anaconda2/envs/python36/lib/python3.6/site-packages/torch/lib/include/TH -I/home/peng/anaconda2/envs/python36/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/cuda-9.1/bin/include -I/home/peng/anaconda2/envs/python36/include/python3.6m --compiler-options '-fPIC' --expt-extended-lambda -std=c++11 -c /home/peng/pytorch-seg-new/lib/LibInplaceABN/modules/src/inplace_abn_cuda.cu -o inplace_abn_cuda.cuda.o
/bin/sh: 1: /usr/local/cuda-9.1/bin/bin/nvcc: not found
[2/5] /usr/local/cuda-9.1/bin/bin/nvcc -DTORCH_EXTENSION_NAME=inplace_abn -I/home/peng/anaconda2/envs/python36/lib/python3.6/site-packages/torch/lib/include -I/home/peng/anaconda2/envs/python36/lib/python3.6/site-packages/torch/lib/include/TH -I/home/peng/anaconda2/envs/python36/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/cuda-9.1/bin/include -I/home/peng/anaconda2/envs/python36/include/python3.6m --compiler-options '-fPIC' --expt-extended-lambda -std=c++11 -c /home/peng/pytorch-seg-new/lib/LibInplaceABN/modules/src/inplace_abn_cuda_half.cu -o inplace_abn_cuda_half.cuda.o
FAILED: inplace_abn_cuda_half.cuda.o 
/usr/local/cuda-9.1/bin/bin/nvcc -DTORCH_EXTENSION_NAME=inplace_abn -I/home/peng/anaconda2/envs/python36/lib/python3.6/site-packages/torch/lib/include -I/home/peng/anaconda2/envs/python36/lib/python3.6/site-packages/torch/lib/include/TH -I/home/peng/anaconda2/envs/python36/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/cuda-9.1/bin/include -I/home/peng/anaconda2/envs/python36/include/python3.6m --compiler-options '-fPIC' --expt-extended-lambda -std=c++11 -c /home/peng/pytorch-seg-new/lib/LibInplaceABN/modules/src/inplace_abn_cuda_half.cu -o inplace_abn_cuda_half.cuda.o
/bin/sh: 1: /usr/local/cuda-9.1/bin/bin/nvcc: not found
[3/5] c++ -MMD -MF inplace_abn.o.d -DTORCH_EXTENSION_NAME=inplace_abn -I/home/peng/anaconda2/envs/python36/lib/python3.6/site-packages/torch/lib/include -I/home/peng/anaconda2/envs/python36/lib/python3.6/site-packages/torch/lib/include/TH -I/home/peng/anaconda2/envs/python36/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/cuda-9.1/bin/include -I/home/peng/anaconda2/envs/python36/include/python3.6m -fPIC -std=c++11 -O3 -c /home/peng/pytorch-seg-new/lib/LibInplaceABN/modules/src/inplace_abn.cpp -o inplace_abn.o
FAILED: inplace_abn.o 
c++ -MMD -MF inplace_abn.o.d -DTORCH_EXTENSION_NAME=inplace_abn -I/home/peng/anaconda2/envs/python36/lib/python3.6/site-packages/torch/lib/include -I/home/peng/anaconda2/envs/python36/lib/python3.6/site-packages/torch/lib/include/TH -I/home/peng/anaconda2/envs/python36/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/cuda-9.1/bin/include -I/home/peng/anaconda2/envs/python36/include/python3.6m -fPIC -std=c++11 -O3 -c /home/peng/pytorch-seg-new/lib/LibInplaceABN/modules/src/inplace_abn.cpp -o inplace_abn.o
/home/peng/pytorch-seg-new/lib/LibInplaceABN/modules/src/inplace_abn.cpp:1:29: fatal error: torch/extension.h: No such file or directory
compilation terminated.
[4/5] c++ -MMD -MF inplace_abn_cpu.o.d -DTORCH_EXTENSION_NAME=inplace_abn -I/home/peng/anaconda2/envs/python36/lib/python3.6/site-packages/torch/lib/include -I/home/peng/anaconda2/envs/python36/lib/python3.6/site-packages/torch/lib/include/TH -I/home/peng/anaconda2/envs/python36/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/cuda-9.1/bin/include -I/home/peng/anaconda2/envs/python36/include/python3.6m -fPIC -std=c++11 -O3 -c /home/peng/pytorch-seg-new/lib/LibInplaceABN/modules/src/inplace_abn_cpu.cpp -o inplace_abn_cpu.o
ninja: build stopped: subcommand failed.

**Comment by zsp1993** [comment]
I don't know why [1/5] /usr/local/cuda-9.1/bin/bin/nvcc has two bin

**Comment by sunggukcha** [comment]
I am also suffered from the same problem, 
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

I am using python3.6, torch>1.0.0, CUDA9.2, and appropriate cudnn.

**Comment by sbelharbi** [comment]
Hi,
   I am having a similar issue. Any updates? thanks!

**Comment by sbelharbi** [comment]
Fix: https://github.com/mapillary/inplace_abn/issues/106#issuecomment-475460496

**Comment by charlesCXK** [comment]
`/bin/sh: 1: /usr/local/cuda-9.1/bin/bin/nvcc: not found`
It is because in `/home/peng/anaconda2/envs/python36/lib/python3.6/site-packages/torch/utils/cpp_extension.py`, the function **__find_cuda_home_** finds the wrong cuda_home variable. So you can modify the py tile, I mean, modify the cuda_home variable it finds, such as delete a '/bin' in it, and you will run Inplace ABN correctly.

**Comment by rudylyh** [comment]
modify the torch source code /usr/local/lib/python3.5/dist-packages/torch/utils/cpp_extension.py, and change ['ninja', '-v'] in line 759 to ['ninja', '--v']

**Comment by rudylyh** [comment]
This is because PyTorch failed to build the InplaceABN library. Normally, there should have some files like inplace_abn.so and build.ninja in /tmp/torch_extensions/inplace_abn/, if the just-in-time compile is successful. The failure could be caused by many factors, including gcc, cuda, ninja, pytorch. 
It works for me with the combination of gcc7.3+cuda10.1+ninja1.9+pytorch0.4.1.
Took me two days to figure out :D

**Comment by vakkov** [comment]
Try installing ninja in such a way - https://www.claudiokuenzler.com/blog/756/install-newer-ninja-build-tools-ubuntu-14.04-trusty#.WxYrvFMvzJw

**Comment by ducksoup** [comment]
This is fixed since `v.1.0.0`.

**Comment by songyuc** [comment]
Hi, @ducksoup Lorenzo, I met this problem again today.

**Comment by 8secz-johndpope** [comment]
this fixed things for me - https://github.com/mapillary/inplace_abn/issues/106

**Comment by xiaoaoran** [comment]
I met this problem again. My code is able to run successfully in pycharm, but meet this problem when runinng in the terminal under same virtual env.  

Anyone knows why? Appriciate.

**Comment by LightingMc** [comment]
@xiaoaoran I also am facing a similar issue. My code runs in a jupyter notebook, but not from a .py file via the terminal.

**Comment by Jichao-Wang** [comment]
I record the solution for your problem in [blog](https://blog.csdn.net/ytrewq121/article/details/126394736).

**Comment by prashant-dn** [comment]
> I record the solution for your problem in [blog](https://blog.csdn.net/ytrewq121/article/details/126394736).

Github is not chinese. English would be better.

**Comment by PeleWang** [comment]
> > I record the solution for your problem in [blog](https://blog.csdn.net/ytrewq121/article/details/126394736).
> 
> Github is not chinese. English would be better.

The solution is right there if you are aware of google translate.

**Comment by prashant-dn** [comment]
@PeleWang there is this simpler and more understandable language called "English", if you are aware of it...

**Comment by PeleWang** [comment]
> @PeleWang there is this simpler and more understandable language called "English", if you are aware of it...

That's not a fact that's an opinion from someone who's too lazy to translate. BTW, what else was I using to give you a hard time?

**Comment by prashant-dn** [comment]
> > @PeleWang there is this simpler and more understandable language called "English", if you are aware of it...
> 
> That's not a fact that's an opinion from someone who's too lazy to translate. BTW, what else was I using to give you a hard time?

Yeah someone was definitely too uneducated/stubborn to think that his messy language can be a very good thing to share here. And you got too-less-work to defend your brother. Yeah you did give me a hard time with that virus.

**Comment by PeleWang** [comment]
> > > @PeleWang there is this simpler and more understandable language called "English", if you are aware of it...
> > 
> > 
> > That's not a fact that's an opinion from someone who's too lazy to translate. BTW, what else was I using to give you a hard time?
> 
> Yeah someone was definitely too uneducated/stubborn to think that his messy language can be a very good thing to share here. And you got too-less-work to defend your brother. Yeah you did give me a hard time with that virus.

There you go. Get it out your system very good for you mental health.

**Comment by vTuanpham** [comment]
I run this command sudo apt-get update and build ninja from source via python and it suddenly work again

**Comment by Aukture** [comment]
Adding C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.38.33130\bin\Hostx86\x86 to environmental variables  solved the problem 
Don't forget to restart terminal/system after this.
Note: I'm on Windows 11.

**Comment by RyanbowZ** [comment]
If you already installed ninja on ubuntu and tried other methods but still suffer from this problem, you can check whether you installed ninja both on python pip and ubuntu environment, they will cause conflict!
I tried almost every other approach on the Internet, but finally I resolved this by:
`pip uninstall ninja`
