### ISSUE TITLE
Multi-card overhead issue

### ISSUE THREAD

**Issue by geekboood** [mapillary/inplace_abn#107]
Recently I tried to use the InPlaceABNSync in my model. My total train set has 3456 images, and when I train it by using single card and InPlaceABN with batchsize equals to 6, a single epoch takes me 550s (which means about 1s each iteration). Compared with InPlaceABN, I use two cards with the same configuration, and it takes about 3.5s each iteration. It is 3.5x slower. Is that normal?

**Comment by rotabulo** [comment]
@geekboood I guess you meant `InPlaceABNSync` in the latter case. What running time do you get if you use `InPlaceABN` on two gpus ?

**Comment by geekboood** [comment]
@rotabulo I just have used it on single GPU.

**Comment by rotabulo** [comment]
@geekboood `InPlaceABNSync` delivers negligible overhead compared to `InPlaceABN`, so you might have issues that do not depend on that. So, you can train on the multi-gpu setting with `InPlaceABN` (no sync) and validate the hypothesis.

**Comment by geekboood** [comment]
@rotabulo Ok, I will try it immediately.

**Comment by geekboood** [comment]
@rotabulo I still got ~3.5 seconds per iteration. Perhaps I have some problem in the usage of `DistributedDataParallel`.

**Comment by geekboood** [comment]
@rotabulo It is my fault. Previously I use the code which is compatible with Pytorch 0.4.1 and in that version everything goes well (single card 0.8s / iter and dual card 1.2s / iter). When I update Pytorch to 1.0.1 and use the latest code things get tricky. I am using CUDA9.0 maybe that is the reason. I will stay with  Pytorch 0.4.1. Thank you for your patience!

**Comment by rotabulo** [comment]
@geekboood have you tried cuda 9.2 instead? Our experience is that by moving to PyTorch 1.0 and CUDA 9.2 and recent cudnn we got a speed performance boost

**Comment by geekboood** [comment]
@geekboood Many people share our lab machine and their code rely on old version of Tensorflow, Pytorch, etc. My tutor won't let me upgrade it.
