### ISSUE TITLE
Can't install on Windows

### ISSUE THREAD

**Issue by amaanda** [mapillary/inplace_abn#111]
I've tried simply cloning the repo and adding it to the path, it did not work. I also tried following the steps on this link https://medium.com/@eugenekhvedchenya/why-you-should-start-using-in-place-activated-batchnorm-11a85bb15c06 but it seems to be outdated since there is no setup.py file on this repo.

Any help would be appreciated. Thanks!

**Comment by qih96** [comment]
i also want to know how to make it work? if you solved this problem, pls help me. thinks

**Comment by ducksoup** [comment]
We currently support only Linux systems. Off course, please feel free to post here in case you find a solution for this.
