### ISSUE TITLE
Get useful information when do inference with Mapillary Vistas pre-trained model

### ISSUE THREAD

**Issue by pepeuno** [mapillary/inplace_abn#113]
Hi,

I run this code "python test_vistas.py /path/to/model.pth.tar /path/to/input/folder /path/to/output/folder" on Mapillary Vistas pre-trained model with an image and I get this result: 
![__CRyFzoDOXn6unQ6a3DnQ](https://user-images.githubusercontent.com/49697383/56291253-d9a5a180-611c-11e9-9b7c-e66733ec7b2a.png)

I would like to apply some transformations to the image to make it more clear (now you can see almos tanything), get how many clasess of every instance we have (how many people or how many traffic lights) and include bounding boxes. 

As an example get as an output something like that: 

![what_I_want](https://user-images.githubusercontent.com/49697383/56291591-736d4e80-611d-11e9-9134-2cb02e7fc607.jpg)

Any advice in how can I get that?

Thanks.

**Comment by rotabulo** [comment]
@pepeuno the network we provide addresses plain semantic segmentation, while you are apparently interested in instance-segmentation. You should apply an algorithm such as, e.g.,  mask-RCNN to the Vistas dataset to obtain such a model.

**Comment by ducksoup** [comment]
In an effort to streamline the resolution process we are closing any issue not directly related with the InPlace-ABN _library and scripts_. Please use other channels if you need to contact us about our paper or the Mapillary Vistas dataset.
