### ISSUE TITLE
Difference between ABN, InplaceABN, InplaceABNSync

### ISSUE THREAD

**Issue by charlesCXK** [mapillary/inplace_abn#116]
Hi, after reading the demo code, I have a question: If I use ABN as what `train_imagenet.py` does, and I use 8 gpus to train my model, does this function (ABN) perform sync BatchNorm?

**Comment by charlesCXK** [comment]
From the source code, it seems that `ABN` is just a normal BatchNorm with activation layer?

**Comment by rotabulo** [comment]
@charlesCXK `ABN` is just standard BN + activation; `InplaceABN` is akin to `ABN` but with inplace computation. `InplaceABNSync` is `InplaceABN` but with synchronized across all gpus.

**Comment by charlesCXK** [comment]
@rotabulo 
Thanks!
