### ISSUE TITLE
module 'torch.distributed' has no attribute 'group'

### ISSUE THREAD

**Issue by txfs1926** [mapillary/inplace_abn#119]
the code below triggered the error as the title:
`from inplace_abn import InPlaceABNSync`
error:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-25f11b8917a5> in <module>
----> 1 from inplace_abn import InPlaceABNSync

G:\Anaconda3\lib\site-packages\inplace_abn\__init__.py in <module>
----> 1 from .abn import ABN, InPlaceABN, InPlaceABNSync

G:\Anaconda3\lib\site-packages\inplace_abn\abn.py in <module>
      4 import torch.nn.functional as functional
      5
----> 6 from .functions import *
      7
      8

G:\Anaconda3\lib\site-packages\inplace_abn\functions.py in <module>
    153 def inplace_abn_sync(x, weight, bias, running_mean, running_var,
    154                      training=True, momentum=0.1, eps=1e-05, activation="leaky_relu", activation_param=0.01,
--> 155                      group=distributed.group.WORLD):
    156     return InPlaceABN.apply(x, weight, bias, running_mean, running_var,
    157                             training, momentum, eps, activation, activation_param, group)

AttributeError: module 'torch.distributed' has no attribute 'group'
```
The package is installed by using the command:
`pip install git+https://github.com/mapillary/inplace_abn.git@v1.0.0`

My env:
Windows 10
Python 3.7.1
Pytorch 1.1.0
cuda 10.2

Thanks!

**Comment by ducksoup** [comment]
I've tried to reproduce this in both Pytorch 1.1.0 and Pytorch 1.0.1 with no success. As you can see here: https://github.com/pytorch/pytorch/blob/v0.4.1/torch/distributed/__init__.py#L142, the class `group` with the `WORLD` attribute has been a part of `torch.distributed` since at least Pytorch 0.4.1. I suspect this error might be related to your particular installation of Pytorch.

Can you try to run
```python
from torch.distributed import group
```
from a python shell and see if it works?

**Comment by txfs1926** [comment]
Hi @ducksoup , I've tried that and it raised ImportError:
```
>>> from torch.distributed import group
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'group' from 'torch.distributed' (G:\Anaconda3\lib\site-packages\torch\distributed\__init__.py)
```
However, it can be imported from torch.distributed.deprecated:
`from torch.distributed.deprecated import group`

**Comment by ducksoup** [comment]
@txfs1926 This is quite strange. As I said, `from torch.distributed import group` works on all the installations of Pytorch I have access to. This is under Linux though, there might be something Windows-specific at play here. Can you import anything else from `torch.distributed`, e.g. `init_process_group`?

In any case, since `from torch.distributed.deprecated import group` seems to work for you I would suggest to use that as a work-around for now.

**Comment by txfs1926** [comment]
Hi,  It looks like I can only import these from torch.distributed.
![20190706214932](https://user-images.githubusercontent.com/44914789/60757151-79e2d680-a039-11e9-97ea-7a49647e2b6e.jpg)

Then I checked the https://github.com/pytorch/pytorch/blob/v1.1.0/torch/distributed/__init__.py and it seems that, comparing to v0.4.1, lots of methods are removed in that of v1.1.0.

Finally, I revised all `import torch.distributed as distributed` to `import torch.distributed.deprecated as distributed` in source codes and then `import inplace_abn` can be executed without raising error.
Thanks for your helping!

**Comment by y78h11b09** [comment]
> the code below triggered the error as the title:
> `from inplace_abn import InPlaceABNSync`
> error:
> 
> ```
> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> <ipython-input-1-25f11b8917a5> in <module>
> ----> 1 from inplace_abn import InPlaceABNSync
> 
> G:\Anaconda3\lib\site-packages\inplace_abn\__init__.py in <module>
> ----> 1 from .abn import ABN, InPlaceABN, InPlaceABNSync
> 
> G:\Anaconda3\lib\site-packages\inplace_abn\abn.py in <module>
>       4 import torch.nn.functional as functional
>       5
> ----> 6 from .functions import *
>       7
>       8
> 
> G:\Anaconda3\lib\site-packages\inplace_abn\functions.py in <module>
>     153 def inplace_abn_sync(x, weight, bias, running_mean, running_var,
>     154                      training=True, momentum=0.1, eps=1e-05, activation="leaky_relu", activation_param=0.01,
> --> 155                      group=distributed.group.WORLD):
>     156     return InPlaceABN.apply(x, weight, bias, running_mean, running_var,
>     157                             training, momentum, eps, activation, activation_param, group)
> 
> AttributeError: module 'torch.distributed' has no attribute 'group'
> ```
> 
> The package is installed by using the command:
> `pip install git+https://github.com/mapillary/inplace_abn.git@v1.0.0`
> 
> My env:
> Windows 10
> Python 3.7.1
> Pytorch 1.1.0
> cuda 10.2
> 
> Thanks!

Hi, your question has been solved ? i meet the same error because of running on windows
