### ISSUE TITLE
weight and x must have the same type (forward at src/inplace_abn.cpp:60)

### ISSUE THREAD

**Issue by khoshsirat** [mapillary/inplace_abn#120]
Hi,

I'm using [apex.amp](https://github.com/NVIDIA/apex) for half precision.
On the older implementation (before today's update) I was able to use _amp_ with opt_level='O1'.
But today I updated the inplace_abn module and it's not working with _amp_ anymore.
It appears that the new update does not work with fp16.

Here is part of the error:
`
/usr/local/lib/python3.6/dist-packages/inplace_abn/functions.py in forward(ctx, x, weight, bias, running_mean, running_var, training, momentum, eps, activation, activation_param, group)
96
97         # Transform x
---> 98         _backend.forward(x, mean, var, weight, bias, ctx.eps, ctx.activation, ctx.activation_param)
99
100         # Save for backward

RuntimeError: weight and x must have the same type (forward at src/inplace_abn.cpp:60)
frame #0: std::function<std::string ()>::operator()() const + 0x11 (0x7fdefc7ca441 in /usr/local/lib/python3.6/dist-packages/torch/lib/libc10.so)
frame #1: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x2a (0x7fdefc7c9d7a in /usr/local/lib/python3.6/dist-packages/torch/lib/libc10.so)
frame #2: forward(at::Tensor&, at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, c10::optional<at::Tensor> const&, float, Activation, float) + 0x515 (0x7fdef9a5f9a5 in /usr/local/lib/python3.6/dist-packages/inplace_abn/_backend.cpython-36m-x86_64-linux-gnu.so)
`

**Comment by ducksoup** [comment]
This is a limitation of the current implementation, I'm working on a patch to restore full compatibility with Apex. This will hopefully be released as inplace_abn 1.0.1 before the end of the week.

**Comment by ducksoup** [comment]
@khoshsirat 1.0.1 should restore Apex compatibility. Please let me know if you encounter other issues when running mixed-precision training!
