### ISSUE TITLE
leaky relu slope parameter is not defined [bug]

### ISSUE THREAD

**Issue by AmeetR** [mapillary/inplace_abn#121]
I'm attempted to test vistas in order to train on my own datasets, in order to do this, I'm trying to use to test_vistas.py script. It seems that the parameter 'slope' is passed into InplaceABN and ABN. However, I'm pretty sure that these functions refer to this parameter as activation_param, they seem to mean the same thing mathematicallly. I tried changing slope to activate_param but it gave the same issues.

**Comment by ducksoup** [comment]
I commited a fix to master, can you please try it and confirm that it works?

**Comment by AmeetR** [comment]
Thanks! This worked.
