### ISSUE TITLE
error: identifier "std::log1p" is undefined in device code...

### ISSUE THREAD

**Issue by ngunauj** [mapillary/inplace_abn#123]
```
include/cuda_utils.cuh(116): error: calling a constexpr __host__ function("std::log1p") from a __device__ function("reduce< ::Float2<float> ,  ::GradOp<float, float,  ::at::PackedTensorAccessor<float, (unsigned long)3ul,  ::at::RestrictPtrTraits, int> , ( ::Activation)1> ,  ::at::PackedTensorAccessor<float, (unsigned long)3ul,  ::at::RestrictPtrTraits, int> > ") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

include/cuda_utils.cuh(116): error: identifier "std::log1p" is undefined in device code

include/cuda_utils.cuh(116): error: calling a constexpr __host__ function("std::log1p") from a __device__ function("reduce< ::Float2<float> ,  ::GradOp<float, float,  ::at::PackedTensorAccessor<float, (unsigned long)3ul,  ::at::RestrictPtrTraits, long> , ( ::Activation)1> ,  ::at::PackedTensorAccessor<float, (unsigned long)3ul,  ::at::RestrictPtrTraits, long> > ") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

include/cuda_utils.cuh(116): error: identifier "std::log1p" is undefined in device code

include/inplace_abn.h(79): warning: calling a constexpr __host__ function("std::log1p") from a __host__ __device__ function("ActivationFn< ::c10::Half, ( ::Activation)1> ::backward") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

4 errors detected in the compilation of "/home/users/jss/tmp/tmp/tmpxft_00006dbf_00000000-6_inplace_abn_cuda.cpp1.ii".
error: command '/usr/local/cuda-9.2/bin/nvcc' failed with exit status 1

```

**Comment by ngunauj** [comment]
my pytorch version is 1.1.0

**Comment by ducksoup** [comment]
@ngunauj I suspect this is a CUDA 9.2 compatibility issue. I'll look for a work-around, in the meanwhile can you upgrade to the latest CUDA (10.1) and try again?

**Comment by ngunauj** [comment]
> @ngunauj I suspect this is a CUDA 9.2 compatibility issue. I'll look for a work-around, in the meanwhile can you upgrade to the latest CUDA (10.1) and try again?

I don't have permission to upgrade CUDA, so I used the old version of inplace_abn..

**Comment by rotorliu** [comment]
My cuda version is 10.1
but there are still same errors.

**Comment by ngunauj** [comment]
> My cuda version is 10.1
> but there are still same errors.
> 
> GPU:RTX2080ti
> Container:nvcr.io/nvidia/pytorch:19.06-py3(Pytorch 1.1.0)

What is the gcc version?

**Comment by rotorliu** [comment]
> > My cuda version is 10.1
> > but there are still same errors.
> > GPU:RTX2080ti
> > Container:nvcr.io/nvidia/pytorch:19.06-py3(Pytorch 1.1.0)
> 
> What is the gcc version?

gcc version 5.4.0 20160609

**Comment by ducksoup** [comment]
@rotorliu can you post the errors you are getting?

**Comment by rotorliu** [comment]
include/cuda_utils.cuh(116): error: calling a constexpr __host__ function("std::log1p") from a __device__ function("reduce<    ::Float2<float> ,     ::GradOp<float, float,  ::at::PackedTensorAccessor<float, (unsigned long)3ul,  ::at::RestrictPtrTraits, int> , (    ::Activation)1> ,  ::at::PackedTensorAccessor<float, (unsigned long)3ul,  ::at::RestrictPtrTraits, int> > ") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

include/cuda_utils.cuh(116): error: identifier "std::log1p" is undefined in device code

include/cuda_utils.cuh(116): error: calling a constexpr __host__ function("std::log1p") from a __device__ function("reduce<    ::Float2<float> ,     ::GradOp<float, float,  ::at::PackedTensorAccessor<float, (unsigned long)3ul,  ::at::RestrictPtrTraits, long> , (    ::Activation)1> ,  ::at::PackedTensorAccessor<float, (unsigned long)3ul,  ::at::RestrictPtrTraits, long> > ") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

include/cuda_utils.cuh(116): error: identifier "std::log1p" is undefined in device code

include/inplace_abn.h(79): warning: calling a constexpr __host__ function("std::log1p") from a __host__ __device__ function("ActivationFn< ::c10::Half, (    ::Activation)1> ::backward") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

4 errors detected in the compilation of "/tmp/tmpxft_000001f6_00000000-6_inplace_abn_cuda.cpp1.ii".
error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1

**Comment by ducksoup** [comment]
@rotorliu @ngunauj I'm trying to reproduce your error, but to no avail. I think it might have to do with the specific versions of CUDA / gcc you are using, but I need to investigate further to find a proper solution.

In the meanwhile, you can try as a work-around to replace in `include/inplace_abn.h`, line 79, this:
```c++
y_act = std::log1p(y_act / static_cast<scalar_t>(activation_param));
```
with this:
```c++
y_act = std::log(1 + y_act / static_cast<scalar_t>(activation_param));
```

**Comment by rotorliu** [comment]
> @rotorliu @ngunauj I'm trying to reproduce your error, but to no avail. I think it might have to do with the specific versions of CUDA / gcc you are using, but I need to investigate further to find a proper solution.
> 
> In the meanwhile, you can try as a work-around to replace in `include/inplace_abn.h`, line 79, this:
> 
> ```c++
> y_act = std::log1p(y_act / static_cast<scalar_t>(activation_param));
> ```
> 
> with this:
> 
> ```c++
> y_act = std::log(1 + y_act / static_cast<scalar_t>(activation_param));
> ```

@ducksoup 
Great! It works! Thank you
