### ISSUE TITLE
Support for cpu-only pytorch

### ISSUE THREAD

**Issue by miquelmarti** [mapillary/inplace_abn#129]
Hi,

I have pytorch-cpu 1.1.0 in a development machine with no GPU. I can't install your package as I get the following error both installing with pip or with python setup.py install

```
OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
```

Is your package only supported for CUDA-enabled pytorch or is there a way to get it to work for pytorch-cpu too?

**Comment by ducksoup** [comment]
This is now added in `v1.0.5`.

**Comment by jhagege** [comment]
> This is now added in `v1.0.5`.

Works great on v1.0.5, any chance it could be supported on latest versions, such as v1.0.7? 
Thanks.
