### ISSUE TITLE
ninja error

### ISSUE THREAD

**Issue by yyfyan** [mapillary/inplace_abn#132]
/usr/local/lib/python2.7/dist-packages/torch/utils/cpp_extension.py:118: UserWarning: 

                               !! WARNING !!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (c++) may be ABI-incompatible with PyTorch!
Please use a compiler that is ABI-compatible with GCC 4.9 and above.
See https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html.

See https://gist.github.com/goldsborough/d466f43e8ffc948ff92de7486c5216d6
for instructions on how to install GCC 4.9 or higher.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                              !! WARNING !!

  warnings.warn(ABI_INCOMPATIBILITY_WARNING.format(compiler))
Traceback (most recent call last):
  File "hrnet32seg.py", line 23, in <module>
    from modules.bn import InPlaceABNSync
  File "/data1/code/cocoAI/EXP/bbe.hrnet32.voc.all.seg/modules/__init__.py", line 1, in <module>
    from .bn import ABN, InPlaceABN, InPlaceABNSync
  File "/data1/code/cocoAI/EXP/bbe.hrnet32.voc.all.seg/modules/bn.py", line 10, in <module>
    from .functions import *
  File "/data1/code/cocoAI/EXP/bbe.hrnet32.voc.all.seg/modules/functions.py", line 19, in <module>
    extra_cuda_cflags=["--expt-extended-lambda"])
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/cpp_extension.py", line 514, in load
    with_cuda=with_cuda)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/cpp_extension.py", line 682, in _jit_compile
    _build_extension_module(name, build_directory)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/cpp_extension.py", line 765, in _build_extension_module
    name, error.output.decode()))
RuntimeError: Error building extension 'inplace_abn': [1/2] c++ -MMD -MF inplace_abn.o.d -DTORCH_EXTENSION_NAME=inplace_abn -I/usr/local/lib/python2.7/dist-packages/torch/lib/include -I/usr/local/lib/python2.7/dist-packages/torch/lib/include/TH -I/usr/local/lib/python2.7/dist-packages/torch/lib/include/THC -I/usr/local/cuda/include -I/usr/local/include/python2.7 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++11 -O3 -c /data1/code/cocoAI/EXP/bbe.hrnet32.voc.all.seg/modules/src/inplace_abn.cpp -o inplace_abn.o
FAILED: inplace_abn.o 
c++ -MMD -MF inplace_abn.o.d -DTORCH_EXTENSION_NAME=inplace_abn -I/usr/local/lib/python2.7/dist-packages/torch/lib/include -I/usr/local/lib/python2.7/dist-packages/torch/lib/include/TH -I/usr/local/lib/python2.7/dist-packages/torch/lib/include/THC -I/usr/local/cuda/include -I/usr/local/include/python2.7 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++11 -O3 -c /data1/code/cocoAI/EXP/bbe.hrnet32.voc.all.seg/modules/src/inplace_abn.cpp -o inplace_abn.o
/data1/code/cocoAI/EXP/bbe.hrnet32.voc.all.seg/modules/src/inplace_abn.cpp:66:16: error: expected constructor, destructor, or type conversion before ‘(’ token
 PYBIND11_MODULE(TORCH_EXTENSION_NAME, m) {
                ^
ninja: build stopped: subcommand failed.

inplace_abn.cpp:66:16: error: expected constructor, destructor, or type conversion before ‘(’ token
 PYBIND11_MODULE(TORCH_EXTENSION_NAME, m) {

**Comment by yyfyan** [comment]
My env:
pytorch0.4.1
python2.7
gcc 5.4.0
cuda:9.2

**Comment by yyfyan** [comment]
I use the v0.0.3 branch， Can you give me some solvtion. Thanks. 
@kardotim @rotabulo @ducksoup @pkontschieder

**Comment by ducksoup** [comment]
I'm sorry but we can't offer support for InPlace-ABN versions previous to `1.0.0` anymore.
Thank you for your understanding.
