### ISSUE TITLE
cuda-10.0 build error

### ISSUE THREAD

**Issue by blakeliu** [mapillary/inplace_abn#134]
gcc version 5.4.0
OS：Ubuntu16.4
CUDA Version: 10.0
pytorch： 1.1.0

`pip install git+https://github.com/mapillary/inplace_abn.git@v1.0.6`
###  error!
**include/cuda_utils.cuh(116): error: identifier "std::log1p" is undefined in device code
    
include/inplace_abn.h(79): warning: calling a constexpr __host__ function("std::log1p") from a __host__ __device__ function("ActivationFn< ::c10::Half, ( ::Activation)1> ::backward") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.
    
4 errors detected in the compilation of "/tmp/tmpxft_00005470_00000000 6_inplace_abn_cuda.cpp1.ii".
    error: command '/usr/local/cuda-10.0/bin/nvcc' failed with exit status 1
    ----------------------------------------
ERROR: Command "/home/blake/anaconda3/envs/pytorch/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-req-build-wb90i3_w/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-nyk5gw8c/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-req-build-wb90i3_w/**

**Comment by meshiang** [comment]
I also stumble upon this error when I use Pytorch 1.1 and cuda 9.2
My quick solution was to upgrade to Pytorch 1.2 and cuda 9.2. Hope this helps!

**Comment by ducksoup** [comment]
@blakeliu @meshiang I implemented a possible fix for this and other related errors, can you try again with the latest master?

**Comment by meshiang** [comment]
I tried v1.0.7 and I successfully installed it. 
I am using Pytorch 1.1 and Cuda 10.0.

**Comment by blakeliu** [comment]
@meshiang You are right！

**Comment by ducksoup** [comment]
@meshiang @blakeliu good, I'll close the issue and add the fixes to the next release. Thank you for your bug report!
