### ISSUE TITLE
can not compile base on Win10 + PyTorch 1.0 + VS2017  +Cuda 10.0.130 

### ISSUE THREAD

**Issue by 18608003987** [mapillary/inplace_abn#137]
Is there anyone can compile it on   Win10 + PyTorch 1.0 + VS2017 +Cuda 10.0.130 ?

when I compile it I got the error message 👎 
-----------------------------------------------------------------------------------------------
src\inplace_abn_cpu.cpp(15): warning C4244: “return”: 从“int64_t”转换到“int32_t”，可能丢失数据
src\inplace_abn_cpu.cpp(130): error C2440: “初始化”: 无法从“c10::ScalarType”转换为“const at::Type &”
src\inplace_abn_cpu.cpp(130): note: 原因如下: 无法从“c10::ScalarType”转换为“const at::Type”
src\inplace_abn_cpu.cpp(130): note: 没有可用于执行该转换的用户定义的转换运算符，或者无法调用该运算符
error: command 'D:\\VS2017\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX64\\x64\\cl.exe' failed with exit status 2
---------------------------------------------------------------------------------------------------
From the change log on Update 08 Jan. 2019, it mentioned 
    **Requires now PyTorch 1.0**

But from the current requirement mentioned on readme, it  has follwing requirements
"NOTE: our code requires **PyTorch v1.1** or later."

From the requirement.txt , it mentioned only need **torch>=1.0**

So, I am confused if I still still have chance to compile base on Win10 + PyTorch 1.0 + VS2017  +Cuda 10.0.130 

Please comments.

**Comment by ducksoup** [comment]
@18608003987 The references to PyTorch 1.0 are outdated, the code actually requires version 1.1. I'll update the README and requirements files accordingly. 

As an aside, I would like to point out that, unfortunately, we are unable to provide support for Windows systems. I'm sorry about that.
