### ISSUE TITLE
InplaceABN doesn't reduce GPU memory usage

### ISSUE THREAD

**Issue by weixianghong** [mapillary/inplace_abn#139]
I am trying to reduce the memory cost of ResNet-101. Below are my modifications to the Bottleneck class. I didn't observe the reduce of memory cost.
```
class Bottleneck(nn.Module):

    expansion = 4
    def __init__(self, inplanes, planes, stride=1, dilation=1, downsample=None, fix_bn=True):
        super(Bottleneck, self).__init__()
        self.conv1 = nn.Conv2d(inplanes, planes, kernel_size=1, stride=stride, bias=False)
        self.bn1 = InPlaceABN(planes)

        self.conv2 = nn.Conv2d(planes, planes, kernel_size=3, stride=1,
                               padding=dilation, dilation=dilation, bias=False)
        self.bn2 = InPlaceABN(planes)
        self.conv3 = nn.Conv2d(planes, planes * 4, kernel_size=1, bias=False)
        self.bn3 = InPlaceABN(planes * 4)
        self.bn3.activation = "identity"
        self.downsample = downsample
        self.stride = stride
        if fix_bn:
            self.bn1.eval()
            self.bn2.eval()
            self.bn3.eval()
            for i in self.bn1.parameters():
                i.requires_grad = False
            for i in self.bn2.parameters():
                i.requires_grad = False
            for i in self.bn3.parameters():
                i.requires_grad = False

    def forward(self, x):
        residual = x

        out = self.conv1(x)
        out = self.bn1(out)

        out = self.conv2(out)
        out = self.bn2(out)

        out = self.conv3(out)
        out = self.bn3(out)

        if self.downsample is not None:
            residual = self.downsample(x)

        out = residual + out

        return F.relu(out, inplace=True)
```

**Comment by ducksoup** [comment]
@weixianghong are you passing `fix_bn=True` while comparing memory consumption?

**Comment by weixianghong** [comment]
@ducksoup  I tried both ```fix_bn=False``` and ```fix_bn=True```, and didn't observe memory usage reduce in either case.

**Comment by ducksoup** [comment]
@weixianghong how are you measuring memory usage exactly?

**Comment by weixianghong** [comment]
@ducksoup I am using this [script](https://github.com/jacobkimmel/pytorch_modelsize)

**Comment by weixianghong** [comment]
@ducksoup I am training a very deep ResNet on V100 GPU, with input image size as 240*320. Each GPU can only hold one image. If I increased the image size to 360*480, the training will be killed due to large memory request.
I am expecting that InplaceABN can reduce the memory consumption of my model, so that I can increased the image size. However, after I replace the Bottleneck class of my ResNet as above, it still cannot work with input of size 360*480.

**Comment by rotabulo** [comment]
@weixianghong the increasing factor of the total number of input pixels in your example is 2.25x, which roughly translates into an equivalent increase factor in memory. InplaceABN in a ResNet with identity mapping can lead to gains not larger than 2x, but this gain is reduced to 1.5x in the case of standard Resnet (which is the one you implemented).
