### ISSUE TITLE
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation

### ISSUE THREAD

**Issue by mathmanu** [mapillary/inplace_abn#14]
I am using Python 3.5, Pytorch 0.3.1

I get the following error when using any of the InPlaceABN variants:
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation

~~I looked through the code of in-place abn and found the following lines in functions.py
            # Update running stats
            running_mean.mul_((1 - ctx.momentum)).add_(ctx.momentum * mean)
            running_var.mul_((1 - ctx.momentum)).add_(ctx.momentum * var * n / (n - 1))
Could these lines be triggering this error? Changing these to non-inplace operations resulted in another error related to storage of variables.~~

Kindly help.

**Comment by rotabulo** [comment]
@mathmanu maybe having a look to https://github.com/mapillary/inplace_abn/issues/6 helps you in fixing the issue.

**Comment by mathmanu** [comment]
Thanks. There was an inplace residual connection that caused the problem. Since there cannot be two back to back in-place operations, that caused an error.
