### ISSUE TITLE
Curious about where to find header files used in c++ when installing

### ISSUE THREAD

**Issue by allenfutaki** [mapillary/inplace_abn#140]
Thanks for your great work.

These are header files used in pytorch.
`#include <ATen/ATen.h>`
`#include <ATen/AccumulateType.h>`
`#include <ATen/cuda/detail/IndexUtils.cuh>`
`#include <c10/cuda/CUDAStream.h>`
`#include <c10/util/Optional.h>`
 
I am curious about how does the [codes](https://github.com/mapillary/inplace_abn/blob/master/src/inplace_abn_cuda.cu) find the path to use these header files to build the pytorch c++ extension.
Thanks.

**Comment by ducksoup** [comment]
@allenfutaki Paths are handled by Pytorch's extension system: https://pytorch.org/docs/stable/cpp_extension.html
