### ISSUE TITLE
failed install

### ISSUE THREAD

**Issue by tetelias** [mapillary/inplace_abn#143]
When running recommended "pip install git+https://github.com/mapillary/inplace_abn.git@v1.0.7"
I get:
Building wheels for collected packages: inplace-abn
  Building wheel for inplace-abn (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/someone/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-clbtj92s/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-clbtj92s/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-vtkrfujw --python-tag cp37
       cwd: /tmp/pip-req-build-clbtj92s/
  Complete output (51 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.7
  creating build/lib.linux-x86_64-3.7/inplace_abn
  copying inplace_abn/_version.py -> build/lib.linux-x86_64-3.7/inplace_abn
  copying inplace_abn/group.py -> build/lib.linux-x86_64-3.7/inplace_abn
  copying inplace_abn/__init__.py -> build/lib.linux-x86_64-3.7/inplace_abn
  copying inplace_abn/abn.py -> build/lib.linux-x86_64-3.7/inplace_abn
  copying inplace_abn/functions.py -> build/lib.linux-x86_64-3.7/inplace_abn
  running build_ext
  building 'inplace_abn._backend' extension
  creating build/temp.linux-x86_64-3.7
  creating build/temp.linux-x86_64-3.7/src
  /usr/bin/nvcc -DWITH_CUDA=1 -Iinclude/ -I/home/someone/anaconda3/lib/python3.7/site-packages/torch/include -I/home/someone/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/someone/anaconda3/lib/python3.7/site-packages/torch/include/TH -I/home/someone/anaconda3/lib/python3.7/site-packages/torch/include/THC -I/home/someone/anaconda3/include/python3.7m -c src/inplace_abn_cuda.cu -o build/temp.linux-x86_64-3.7/src/inplace_abn_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_backend -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++11
  /usr/lib/gcc/x86_64-linux-gnu/5/include/mwaitxintrin.h(36): error: identifier "__builtin_ia32_monitorx" is undefined
  
  /usr/lib/gcc/x86_64-linux-gnu/5/include/mwaitxintrin.h(42): error: identifier "__builtin_ia32_mwaitx" is undefined
  
  /home/someone/anaconda3/lib/python3.7/site-packages/torch/include/c10/util/Half-inl.h(21): error: identifier "__half_as_short" is undefined
  
  include/cuda_utils.cuh(25): error: identifier "__shfl_xor" is undefined
            detected during:
              instantiation of "T WARP_SHFL_XOR(T, int, int, unsigned int) [with T=at::acc_type<double, true>]"
  src/inplace_abn_kernels.cuh(52): here
              instantiation of "void statistics_kernel(at::PackedTensorAccessor<scalar_t, 3UL, at::RestrictPtrTraits, index_t>, at::PackedTensorAccessor<accscalar_t, 1UL, at::RestrictPtrTraits, index_t>, at::PackedTensorAccessor<accscalar_t, 1UL, at::RestrictPtrTraits, index_t>) [with scalar_t=double, accscalar_t=at::acc_type<double, true>, index_t=int32_t]"
  src/inplace_abn_cuda.cu(50): here
              instantiation of "std::tuple<at::Tensor, at::Tensor, at::Tensor> statistics_template<scalar_t,index_t>(const at::Tensor &) [with scalar_t=double, index_t=int32_t]"
  src/inplace_abn_cuda.cu(230): here
  
  include/cuda_utils.cuh(25): error: identifier "__shfl_xor" is undefined
            detected during:
              instantiation of "T WARP_SHFL_XOR(T, int, int, unsigned int) [with T=int]"
  src/inplace_abn_kernels.cuh(53): here
              instantiation of "void statistics_kernel(at::PackedTensorAccessor<scalar_t, 3UL, at::RestrictPtrTraits, index_t>, at::PackedTensorAccessor<accscalar_t, 1UL, at::RestrictPtrTraits, index_t>, at::PackedTensorAccessor<accscalar_t, 1UL, at::RestrictPtrTraits, index_t>) [with scalar_t=double, accscalar_t=at::acc_type<double, true>, index_t=int32_t]"
  src/inplace_abn_cuda.cu(50): here
              instantiation of "std::tuple<at::Tensor, at::Tensor, at::Tensor> statistics_template<scalar_t,index_t>(const at::Tensor &) [with scalar_t=double, index_t=int32_t]"
  src/inplace_abn_cuda.cu(230): here
  
  include/cuda_utils.cuh(25): error: identifier "__shfl_xor" is undefined
            detected during:
              instantiation of "T WARP_SHFL_XOR(T, int, int, unsigned int) [with T=at::acc_type<float, true>]"
  src/inplace_abn_kernels.cuh(52): here
              instantiation of "void statistics_kernel(at::PackedTensorAccessor<scalar_t, 3UL, at::RestrictPtrTraits, index_t>, at::PackedTensorAccessor<accscalar_t, 1UL, at::RestrictPtrTraits, index_t>, at::PackedTensorAccessor<accscalar_t, 1UL, at::RestrictPtrTraits, index_t>) [with scalar_t=float, accscalar_t=at::acc_type<float, true>, index_t=int32_t]"
  src/inplace_abn_cuda.cu(50): here
              instantiation of "std::tuple<at::Tensor, at::Tensor, at::Tensor> statistics_template<scalar_t,index_t>(const at::Tensor &) [with scalar_t=float, index_t=int32_t]"
  src/inplace_abn_cuda.cu(230): here
  
  6 errors detected in the compilation of "/tmp/tmpxft_00005ef5_00000000-7_inplace_abn_cuda.cpp1.ii".
  error: command '/usr/bin/nvcc' failed with exit status 2
  ----------------------------------------
  ERROR: Failed building wheel for inplace-abn
  Running setup.py clean for inplace-abn
Failed to build inplace-abn
Installing collected packages: inplace-abn
  Running setup.py install for inplace-abn ... error
    ERROR: Command errored out with exit status 1:
     command: /home/someone/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-clbtj92s/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-clbtj92s/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-g56d489a/install-record.txt --single-version-externally-managed --compile
         cwd: /tmp/pip-req-build-clbtj92s/
    Complete output (51 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/inplace_abn
    copying inplace_abn/_version.py -> build/lib.linux-x86_64-3.7/inplace_abn
    copying inplace_abn/group.py -> build/lib.linux-x86_64-3.7/inplace_abn
    copying inplace_abn/__init__.py -> build/lib.linux-x86_64-3.7/inplace_abn
    copying inplace_abn/abn.py -> build/lib.linux-x86_64-3.7/inplace_abn
    copying inplace_abn/functions.py -> build/lib.linux-x86_64-3.7/inplace_abn
    running build_ext
    building 'inplace_abn._backend' extension
    creating build/temp.linux-x86_64-3.7
    creating build/temp.linux-x86_64-3.7/src
    /usr/bin/nvcc -DWITH_CUDA=1 -Iinclude/ -I/home/someone/anaconda3/lib/python3.7/site-packages/torch/include -I/home/someone/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/someone/anaconda3/lib/python3.7/site-packages/torch/include/TH -I/home/someone/anaconda3/lib/python3.7/site-packages/torch/include/THC -I/home/someone/anaconda3/include/python3.7m -c src/inplace_abn_cuda.cu -o build/temp.linux-x86_64-3.7/src/inplace_abn_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_backend -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++11
    /usr/lib/gcc/x86_64-linux-gnu/5/include/mwaitxintrin.h(36): error: identifier "__builtin_ia32_monitorx" is undefined
    
    /usr/lib/gcc/x86_64-linux-gnu/5/include/mwaitxintrin.h(42): error: identifier "__builtin_ia32_mwaitx" is undefined
    
    /home/someone/anaconda3/lib/python3.7/site-packages/torch/include/c10/util/Half-inl.h(21): error: identifier "__half_as_short" is undefined
    
    include/cuda_utils.cuh(25): error: identifier "__shfl_xor" is undefined
              detected during:
                instantiation of "T WARP_SHFL_XOR(T, int, int, unsigned int) [with T=at::acc_type<double, true>]"
    src/inplace_abn_kernels.cuh(52): here
                instantiation of "void statistics_kernel(at::PackedTensorAccessor<scalar_t, 3UL, at::RestrictPtrTraits, index_t>, at::PackedTensorAccessor<accscalar_t, 1UL, at::RestrictPtrTraits, index_t>, at::PackedTensorAccessor<accscalar_t, 1UL, at::RestrictPtrTraits, index_t>) [with scalar_t=double, accscalar_t=at::acc_type<double, true>, index_t=int32_t]"
    src/inplace_abn_cuda.cu(50): here
                instantiation of "std::tuple<at::Tensor, at::Tensor, at::Tensor> statistics_template<scalar_t,index_t>(const at::Tensor &) [with scalar_t=double, index_t=int32_t]"
    src/inplace_abn_cuda.cu(230): here
    
    include/cuda_utils.cuh(25): error: identifier "__shfl_xor" is undefined
              detected during:
                instantiation of "T WARP_SHFL_XOR(T, int, int, unsigned int) [with T=int]"
    src/inplace_abn_kernels.cuh(53): here
                instantiation of "void statistics_kernel(at::PackedTensorAccessor<scalar_t, 3UL, at::RestrictPtrTraits, index_t>, at::PackedTensorAccessor<accscalar_t, 1UL, at::RestrictPtrTraits, index_t>, at::PackedTensorAccessor<accscalar_t, 1UL, at::RestrictPtrTraits, index_t>) [with scalar_t=double, accscalar_t=at::acc_type<double, true>, index_t=int32_t]"
    src/inplace_abn_cuda.cu(50): here
                instantiation of "std::tuple<at::Tensor, at::Tensor, at::Tensor> statistics_template<scalar_t,index_t>(const at::Tensor &) [with scalar_t=double, index_t=int32_t]"
    src/inplace_abn_cuda.cu(230): here
    
    include/cuda_utils.cuh(25): error: identifier "__shfl_xor" is undefined
              detected during:
                instantiation of "T WARP_SHFL_XOR(T, int, int, unsigned int) [with T=at::acc_type<float, true>]"
    src/inplace_abn_kernels.cuh(52): here
                instantiation of "void statistics_kernel(at::PackedTensorAccessor<scalar_t, 3UL, at::RestrictPtrTraits, index_t>, at::PackedTensorAccessor<accscalar_t, 1UL, at::RestrictPtrTraits, index_t>, at::PackedTensorAccessor<accscalar_t, 1UL, at::RestrictPtrTraits, index_t>) [with scalar_t=float, accscalar_t=at::acc_type<float, true>, index_t=int32_t]"
    src/inplace_abn_cuda.cu(50): here
                instantiation of "std::tuple<at::Tensor, at::Tensor, at::Tensor> statistics_template<scalar_t,index_t>(const at::Tensor &) [with scalar_t=float, index_t=int32_t]"
    src/inplace_abn_cuda.cu(230): here
    
    6 errors detected in the compilation of "/tmp/tmpxft_00005f1c_00000000-7_inplace_abn_cuda.cpp1.ii".
    error: command '/usr/bin/nvcc' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/someone/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-clbtj92s/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-clbtj92s/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-g56d489a/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.

Google search leads only to this issue with CUDA: "https://github.com/NVIDIA/nccl/issues/29", where the only solution is to "add the CXX flags:
-D_MWAITXINTRIN_H_INCLUDED
-D_FORCE_INLINES
-D__STRICT_ANSI__"
But where would I add them?

**Comment by PRC-Huang** [comment]
The same question ...

**Comment by ducksoup** [comment]
@tetelias Can you please list the versions of CUDA, Pytorch and gcc you are using?

**Comment by yechenzhi** [comment]
how did you solve it?
