### ISSUE TITLE
Question: inplace backward

### ISSUE THREAD

**Issue by vadimkantorov** [mapillary/inplace_abn#146]
Do I understand correctly that grad_input [is computed not inplace](https://github.com/mapillary/inplace_abn/blob/master/src/inplace_abn_cuda.cu#L197)? Is it possible? And if potentially possible, does it make sense to [try to do it inplace either](https://github.com/mapillary/inplace_abn/blob/master/src/inplace_abn_kernels.cuh#L251-L252)? (or maybe PyTorch memory system will quickly recycle the unused grad tensors) Thanks!

**Comment by rotabulo** [comment]
@vadimkantorov to our knowledge, PyTorch should efficiently release the memory once it's not needed anymore, but we have never verified it. I am not sure we can overwrite `input_grad`, since it could be that the same copy is passed to another backward branch (again to be verified).

**Comment by vadimkantorov** [comment]
Thanks!
