### ISSUE TITLE
inplaceabn backward error

### ISSUE THREAD

**Issue by ginobilinie** [mapillary/inplace_abn#149]
Hi, I encounter an inplaceabn backward error when I use InplaceABNSync in my model. Can anyone help?

The detailed error information: 

RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [2, 1024, 16, 16]], which is output 0 of InPlaceABNBackward, is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

Environment:
pytorch 1.2
cuda 10.0

Thanks.

**Comment by ducksoup** [comment]
@ginobilinie this error is a common occurrence when replacing layers in a network architecture with in-place versions, and it's not InplaceABN-specific. Please review your architecture and make sure that no tensor is ever overwritten twice by two separate in-place operations. Are you by any chance replace standard BN with InplaceABN in Pytorch's implementation of ResNet?

**Comment by ginobilinie** [comment]
Thanks. 

I have now made clear the error, I indeed used inplace ops twice (relu(inplace=true))...

**Comment by YousefRabi** [comment]
ducksoup, I am replacing standard BN layers in pytorch's resnet with InPlaceABNSync and getting this error, what do I need to watch out for? I do not have any other inplace operations in the network.
