### ISSUE TITLE
install fatal

### ISSUE THREAD

**Issue by TianMingChen** [mapillary/inplace_abn#151]
![image](https://user-images.githubusercontent.com/20785298/70026117-e73f6700-15d9-11ea-8b71-074d8e0e7bc6.png)
Hi,I install in cuda 9.0,and such problem hapeened,do you have some solution?

**Comment by ducksoup** [comment]
@TianMingChen this is not an InplaceABN issue, but something related to the way your python environment is set up. Do you have `python-dev`, or the equivalent package for your OS, currently installed?

**Comment by TianMingChen** [comment]
> @TianMingChen this is not an InplaceABN issue, but something related to the way your python environment is set up. Do you have `python-dev`, or the equivalent package for your OS, currently installed?

thank you , it have been solved.

**Comment by PurveshChhajed** [comment]
Same issue @TianMingChen can u share the way by which your problem got solved.
