### ISSUE TITLE
ValueError: Unknown activation function none

### ISSUE THREAD

**Issue by tjpulkl** [mapillary/inplace_abn#153]
![image](https://user-images.githubusercontent.com/57160561/71183848-0ae1fd00-22bc-11ea-9522-a8c12ae42e50.png)

I replaced 'modules' to 'libs' and delete old 'libs' repo to use pytorch 1.0.
And do you know this error?
I tried to replace 'relu' to 'leaky relu' but there is same problem like above image.

Plz help me.
Thank you.

**Comment by rotabulo** [comment]
@tjpulkl in the past we used `none` for no activation, but now it became `identity`. Maybe you are still assigning `none` as activation when porting from the old code?

**Comment by tjpulkl** [comment]
![image](https://user-images.githubusercontent.com/57160561/71219869-0ba18000-230a-11ea-9ac1-03b208297401.png)
thank you for your reply. when I changed no activation to identity, it occur another problem.

**Comment by ducksoup** [comment]
@tjpulkl your current issue has nothing to do with the activation function. What the error message you are getting is telling you is that Pytorch's distributed training functionalities are not initialized. These are required when using `InPlaceABNSync`. Please refer to [this page](https://pytorch.org/docs/stable/distributed.html) for further information on the topic.
