### ISSUE TITLE
Could you give me an example code on how to use inplace_abn 

### ISSUE THREAD

**Issue by tjpulkl** [mapillary/inplace_abn#154]
thank you!

**Comment by ducksoup** [comment]
The [scripts](/mapillary/inplace_abn/tree/master/scripts) folder contains extensive code to train and test InPlace-ABN networks, both on image recognition and image segmentation. Please refer to _e.g._ [resnet.py](/mapillary/inplace_abn/blob/master/scripts/models/resnet.py) and [train_imagenet.py](/mapillary/inplace_abn/blob/master/scripts/train_imagenet.py) for examples of how to build networks with InPlace-ABN.
