### ISSUE TITLE
ImportError: cannot import name "_backend"

### ISSUE THREAD

**Issue by wuyang556** [mapillary/inplace_abn#156]
After I finished install inplace_abn,  I want to import this module, then encounter this error. I find a different py file "_backend.pyi" in path "/inplace_abn/inplace_abn/_backend.pyi". Is the suffix of this file wrong ? After I change this file's suffix to .py, it work. But I don't more work to validate this, I doubt whether it work. thx. @peterneubauer

**Comment by ducksoup** [comment]
@wuyang556 are you running your code from inside the main folder of the `inplace_abn` repo by any chance?

To answer your other question, the file is named correctly: pyi is the extension of Python "stub" files.

**Comment by wl082013** [comment]
Me too with the same problem

**Comment by ducksoup** [comment]
@wl082013 see the response above: due to the way module resolution works in Python, running `import inplace_abn` from the main folder of this repo cannot work properly.
