### ISSUE TITLE
fatal error: c10/cuda/CUDAStream.h: No such file or directory  

### ISSUE THREAD

**Issue by Kenneth-X** [mapillary/inplace_abn#159]
$python setup.py install
True
/home/yuxi.xt/software/anaconda3/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
running install
running bdist_egg
running egg_info
writing inplace_abn.egg-info/PKG-INFO
writing dependency_links to inplace_abn.egg-info/dependency_links.txt
writing top-level names to inplace_abn.egg-info/top_level.txt
reading manifest template 'MANIFEST.in'
writing manifest file 'inplace_abn.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
copying inplace_abn/_version.py -> build/lib.linux-x86_64-3.6/inplace_abn
running build_ext
building 'inplace_abn._backend' extension
/usr/local/cuda-9.0/bin/nvcc -DWITH_CUDA=1 -Iinclude/ -I/home/yuxi.xt/software/anaconda3/lib/python3.6/site-packages/torch/lib/include -I/home/yuxi.xt/software/anaconda3/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/home/yuxi.xt/software/anaconda3/lib/python3.6/site-packages/torch/lib/include/TH -I/home/yuxi.xt/software/anaconda3/lib/python3.6/site-packages/torch/lib/include/THC-I/usr/local/cuda-9.0/include -I/home/yuxi.xt/software/anaconda3/include/python3.6m -c src/inplace_abn_cuda.cu -o build/temp.linux-x86_64-3.6/src/inplace_abn_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_backend -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
src/inplace_abn_cuda.cu:6:33: fatal error: c10/cuda/CUDAStream.h: No such file or directory
compilation terminated.
error: command '/usr/local/cuda-9.0/bin/nvcc' failed with exit status 1

**Comment by ducksoup** [comment]
@Kenneth-X which version of Pytorch are you using?

**Comment by Kenneth-X** [comment]
> @Kenneth-X which version of Pytorch are you using?

version 1.0 with cuda 9.0

**Comment by ducksoup** [comment]
As specified in the README, InPlace-ABN requires Pytorch v1.1 or later and CUDA 10 or later. Please update and try again.

**Comment by Kenneth-X** [comment]
thanks，but to match the  requirements of my online environment and c++ project(onnx and tensorRT speed up)
my pytorch and cuda  is not easy to upgrade 
is there any  idea or old version to match 1.0 version with cuda 9.0 ?

**Comment by ducksoup** [comment]
@Kenneth-X Version `0.1.1` is compatible with Pytorch 1.0, but it is missing many improvements and bug-fixes we released later, so I can't really recommend to use it. The code at that stage was not even packaged as an installable pip package, so you would have to download, build and integrate it manually in your project.

The main source of incompatibility between Pytorch 1.0 and later version is in the names of some of the header files such as `c10/cuda/CUDAStream.h` which used to be called `Aten/cuda/CUDAStream.h`. You can try changing that in the source code and see if it's enough, but I can't guarantee anything.

Unfortunately, we don't have the resources to keep compatibility with older versions of Pytorch as breaking changes happen in their code.

**Comment by Kenneth-X** [comment]
thanks a lot  ,i will try for that

**Comment by Caius-Lu** [comment]
> @Kenneth-X Version `0.1.1` is compatible with Pytorch 1.0, but it is missing many improvements and bug-fixes we released later, so I can't really recommend to use it. The code at that stage was not even packaged as an installable pip package, so you would have to download, build and integrate it manually in your project.
> 
> The main source of incompatibility between Pytorch 1.0 and later version is in the names of some of the header files such as `c10/cuda/CUDAStream.h` which used to be called `Aten/cuda/CUDAStream.h`. You can try changing that in the source code and see if it's enough, but I can't guarantee anything.
> 
> Unfortunately, we don't have the resources to keep compatibility with older versions of Pytorch as breaking changes happen in their code.

lude/THC -I/usr/local/cuda-10.0/include -I/home/caius/anaconda3/envs/ccnet/include/python3.7m -c src/inplace_abn_cuda.cu -o build/temp.linux-x86_64-3.7/src/inplace_abn_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_backend -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
src/inplace_abn_cuda.cu:6:33: fatal error: c10/cuda/CUDAStream.h: No such file or directory
 #include <c10/cuda/CUDAStream.h>
                                 ^
compilation terminated.
error: command '/usr/local/cuda-10.0/bin/nvcc' failed with exit status 1
In [2]: torch.__version__                                                       
Out[2]: '1.1.0'


I have got this problem. How can I solve it？

**Comment by Caius-Lu** [comment]
> @Kenneth-X Version `0.1.1` is compatible with Pytorch 1.0, but it is missing many improvements and bug-fixes we released later, so I can't really recommend to use it. The code at that stage was not even packaged as an installable pip package, so you would have to download, build and integrate it manually in your project.
> 
> The main source of incompatibility between Pytorch 1.0 and later version is in the names of some of the header files such as `c10/cuda/CUDAStream.h` which used to be called `Aten/cuda/CUDAStream.h`. You can try changing that in the source code and see if it's enough, but I can't guarantee anything.
> 
> Unfortunately, we don't have the resources to keep compatibility with older versions of Pytorch as breaking changes happen in their code.

https://github.com/mapillary/inplace_abn/issues/159#issuecomment-586698718

**Comment by Caius-Lu** [comment]
> As specified in the README, InPlace-ABN requires Pytorch v1.1 or later and CUDA 10 or later. Please update and try again.

Can you take a look at the following questions? Thank you. #159 (comment)
