### ISSUE TITLE
Question regarding batch size when distributed training of "sync" option

### ISSUE THREAD

**Issue by seungwooYoo** [mapillary/inplace_abn#16]
Hi, 

Firstly thanks for sharing the awesome project 👍 

I have a question regarding BN "sync" option when using distributed training. Question is is BN parameter is also synced for all distributed machines ?

Specifically, let's say I have 2 machines which having 4 GPUs each. 
If I train a network with batch size as 512 and "sync" option with distributed training, then is it correct that all BN parameters from server1 and server2 are aggregated (i.e., 1024 batch sized BN is aggregated) ? 

Thanks in advance :)

**Comment by rotabulo** [comment]
@seungwooYoo The current implementation of the synchronized BN works only on multiple gpus within the same machine and process.

**Comment by seungwooYoo** [comment]
@rotabulo Thanks for answering.
