### ISSUE TITLE
Can not install in GTX1080Ti, CUDA=10.1, PyTorch 1.4!

### ISSUE THREAD

**Issue by linhduongtuan** [mapillary/inplace_abn#165]
Dear Mapillary,
First of all, your work is valuable and I trying to apply it. However, I can not install Inplace-ABN, following the instruction pip install git+https://github.com/mapillary/inplace_abn.git@v1.0.11 or the alternative one. My configuration is Ubuntu 18.04, Pytorch 1.4, GTX 1080Ti with CUDA ver. 10.1. 
The message: 

ERROR: Command errored out with exit status 1:
     command: /home/linh/.conda/envs/CV/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-g6ls7n0j/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-g6ls7n0j/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-g6p0jt8n/install-record.txt --single-version-externally-managed --compile
         cwd: /tmp/pip-req-build-g6ls7n0j/
    Complete output (20 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/inplace_abn
    copying inplace_abn/_version.py -> build/lib.linux-x86_64-3.6/inplace_abn
    copying inplace_abn/group.py -> build/lib.linux-x86_64-3.6/inplace_abn
    copying inplace_abn/abn.py -> build/lib.linux-x86_64-3.6/inplace_abn
    copying inplace_abn/__init__.py -> build/lib.linux-x86_64-3.6/inplace_abn
    copying inplace_abn/functions.py -> build/lib.linux-x86_64-3.6/inplace_abn
    running build_ext
    building 'inplace_abn._backend' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/src
    /home/linh/.conda/envs/CV/bin/x86_64-conda_cos6-linux-gnu-cc -DNDEBUG -fwrapv -O2 -Wall -Wstrict-prototypes -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -fPIC -DWITH_CUDA=1 -Iinclude/ -I/home/linh/.conda/envs/CV/lib/python3.6/site-packages/torch/include -I/home/linh/.conda/envs/CV/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/linh/.conda/envs/CV/lib/python3.6/site-packages/torch/include/TH -I/home/linh/.conda/envs/CV/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/linh/.conda/envs/CV/include/python3.6m -c src/inplace_abn.cpp -o build/temp.linux-x86_64-3.6/src/inplace_abn.o -O3 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_backend -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
    /usr/local/cuda/bin/nvcc -DWITH_CUDA=1 -Iinclude/ -I/home/linh/.conda/envs/CV/lib/python3.6/site-packages/torch/include -I/home/linh/.conda/envs/CV/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/linh/.conda/envs/CV/lib/python3.6/site-packages/torch/include/TH -I/home/linh/.conda/envs/CV/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/linh/.conda/envs/CV/include/python3.6m -c src/inplace_abn_cuda.cu -o build/temp.linux-x86_64-3.6/src/inplace_abn_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_backend -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=sm_61 -std=c++11
    unable to execute '/usr/local/cuda/bin/nvcc': No such file or directory
    error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/linh/.conda/envs/CV/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-g6ls7n0j/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-g6ls7n0j/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-g6p0jt8n/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.

Do you have any suggestion?
Best regards
Linh

**Comment by ducksoup** [comment]
This error indicates that the setup script is not able to automatically locate the position of the CUDA compiler: `unable to execute '/usr/local/cuda/bin/nvcc': No such file or directory`.
Please verify the following:
* Does `/usr/local/cuda/bin/nvcc` exist on your machine?
* Can you compile any other C++/CUDA Pyotorch extension, e.g. by following this tutorial: https://pytorch.org/tutorials/advanced/cpp_extension.html ?
* In case you installed CUDA in a different location, can you please set the env variable `CUDA_HOME={path to the actual cuda root directory on your machine}`, and try again with the InPlace-ABN installation?

**Comment by linhduongtuan** [comment]
Hi Lorenzo,
I fixed it already. Now I'll try your great work with TResNet https://github.com/mrT23/TResNet.
Many thank for your support.
Linh
