### ISSUE TITLE
InPlaceABNSync for training InPlaceABN for testing

### ISSUE THREAD

**Issue by rocketappslab** [mapillary/inplace_abn#171]
Is there any bad effective for a model using InPlaceABNSync for training while using InPlaceABN for testing?

Because I want to use multiple gpus for training while a single gpu for testing.

**Comment by ducksoup** [comment]
@rocketappslab InPlaceABNSync and InPlaceABN are fully compatible (and ABN is too, in case you need to do comparisons with standard BN without changing network structure), so you can freely load saved snapshots from on into the other.
