### ISSUE TITLE
How can I do In-Place "Activated BatchNorm"  with conv1d()

### ISSUE THREAD

**Issue by tjpulkl** [mapillary/inplace_abn#177]
Hi!
       could you please tell me how to do in-place BatchNorm with conv1d().
Con2d() would be like "BatchNorm2d = functools.partial(InPlaceABNSync, activation='none')"
thank you very much.

**Comment by ducksoup** [comment]
Both InPlaceABN and InPlaceABNSync work out of the box on 3-dimensional tensors such as those used with 1D convolutions.
