### ISSUE TITLE
Is GlobalAvgPool2d in modules correct?

### ISSUE THREAD

**Issue by YousefRabi** [mapillary/inplace_abn#178]
In the GlobalAvgPool2d class in scripts/modules.py, you return inputs.view((in_size[0], in_size[1], -1)).mean(dim=2). This is used before the Linear layer which expects n_channels input channels. Is this correct? Shouldn't we be averaging over the spatial dimensions in every feature map instead? Using something like AdaptiveAvgPool2d?

**Comment by rotabulo** [comment]
@YousefRabi it linearizes the spatial dimensions and then applies a mean-reduction on it, so it's correct.

**Comment by YousefRabi** [comment]
@rotabulo oh right, it's (batch, channel, height, width) in PyTorch. Sorry, yup looks fine now. Thanks!
