### ISSUE TITLE
ResNeXt50 ImageNet pretrained model

### ISSUE THREAD

**Issue by mathmanu** [mapillary/inplace_abn#18]
Is it possible to publish ResNeXt50 ImageNet pretrained model if you have it?

Thanks,

**Comment by pkontschieder** [comment]
@mathmanu I am afraid we haven't trained that model so far but you can do it yourself by e.g. modifying this network [config file](https://github.com/mapillary/inplace_abn/blob/master/experiments/resnext101_ipabn-sync_lr_256.json), replacing "resnext101" with "resnext50" and potentially changing some of the hyper-parameters according to your preferences.

**Comment by mathmanu** [comment]
Thanks. I'll try to do that.
