### ISSUE TITLE
ABN

### ISSUE THREAD

**Issue by libonwpu** [mapillary/inplace_abn#185]
Hi,
from the models, I found they utilize the ABN but not InPlaceABN. So, what's the reason? If I want to use the inplace abn, should I modify the ABN to InPlaceABN in the model definition?

thanks

**Comment by ducksoup** [comment]
Yes, `ABN` is used as a default parameter in the constructors, but you should pass `InPlaceABN` or `InPlaceABNSync` if you want the models to use InPlace-ABN.

**Comment by libonwpu** [comment]
thanks libo 邮箱：libo@nwpu.edu.cn 签名由 网易邮箱大师 定制 On 09/01/2020 22:17, Lorenzo Porzi wrote: Yes, ABN is used as a default parameter in the constructors, but you should pass InPlaceABN or InPlaceABNSync if you want the models to use InPlace-ABN. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
