### ISSUE TITLE
Installation Error, Pytorch=1.4.0, CUDA=10.0, gcc=7.5.0

### ISSUE THREAD

**Issue by DonaldRR** [mapillary/inplace_abn#187]
I encountered installation error. I really have no idea. May that be the problem of the compiler or the torch version? I have hightlighted the command it crashed.

--------------------------------------------------------
running install
running bdist_egg
running egg_info
writing inplace_abn.egg-info/PKG-INFO
writing dependency_links to inplace_abn.egg-info/dependency_links.txt
writing top-level names to inplace_abn.egg-info/top_level.txt
reading manifest template 'MANIFEST.in'
writing manifest file 'inplace_abn.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
copying inplace_abn/_version.py -> build/lib.linux-x86_64-3.6/inplace_abn
running build_ext
building 'inplace_abn._backend' extension
**x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DWITH_CUDA=1 -I/data/projects/face_parsing/inplace_abn/include -I/home/zhouyiming/.local/lib/python3.6/site-packages/torch/include -I/home/zhouyiming/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/zhouyiming/.local/lib/python3.6/site-packages/torch/include/TH -I/home/zhouyiming/.local/lib/python3.6/site-packages/torch/include/THC -I/data/cuda/cuda-10.0/cuda/include -I/usr/include/python3.6m -c src/inplace_abn.cpp -o build/temp.linux-x86_64-3.6/src/inplace_abn.o -O3 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_backend -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
x86_64-linux-gnu-gcc: internal compiler error: Killed (program cc1plus)**
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 4

**Comment by ducksoup** [comment]
@DonaldRR the log says "internal compiler error", so my guess is that this could be a compiler issue, and not something related to InPlace ABN specifically. Are you able e.g. to install Pytorch from source?

**Comment by DonaldRR** [comment]
> @DonaldRR the log says "internal compiler error", so my guess is that this could be a compiler issue, and not something related to InPlace ABN specifically. Are you able e.g. to install Pytorch from source?

You are right. I built the Pytorch from source with the compatible CUDA configurations and it did good.

**Comment by ducksoup** [comment]
@DonaldRR good to hear that rebuilding Pytorch solved your issue, closing this now.
