### ISSUE TITLE
Will the inplace_abn support gpu architecture 'compute_86' of 30 series GPUs?

### ISSUE THREAD

**Issue by pppLang** [mapillary/inplace_abn#192]
Thanks very much for the outstanding work.

I recently encountered a problem when installing this module on a new server ： 

> nvcc fatal   : Unsupported gpu architecture 'compute_86'

Will this be further fixed？

**Comment by ducksoup** [comment]
@pppLang This is a `nvcc` issue, not an `inplace_abn` issue: the version of CUDA you have on your system does not support `compute_86`.
