### ISSUE TITLE
Any idea why this only works on monotonic activation functions?

### ISSUE THREAD

**Issue by bsugerman** [mapillary/inplace_abn#199]
I've tried some changes to the activation functions in `include/inplace_abn.h`. All the functions are differentiable and invertible (i.e. if the activation function is *y=f(x)*, you can compute *x=f^{-1}(y)*), but whenever one is non-monotonic (slope changes from positive to negative, like swish) the inplace_abn function causes models to fail to optimize. I don't know if anyone is still monitoring this repo, but I'm quite curious why that is happening.

**Comment by vincrichard** [comment]
Hello, I don't have the answer to your question but it seems to me that swish is not invertible. What function did you use to compute the inverse ?
