### ISSUE TITLE
How many gpus did you use in the semantic segmentation task.

### ISSUE THREAD

**Issue by alexalex1234** [mapillary/inplace_abn#20]
Hi, I want to repeat your experiments on cityscapes datasets.
I use the inplace bn  and your widerresnet but it also consume lots of memory of ecah gpu
So I want to know : How many gpus did you use in the semantic segmentation task?
Thanks

**Comment by rotabulo** [comment]
@alexalex1234 As we wrote in the arXiv paper (Sec. 4): 
> Experiments were run and timed on machines comprising four NVIDIA Titan Xp cards (with 12GB of RAM each).

You can then find the batch sizes and crop sizes we used in Tables 3 and 4. 
I hope this answers your question.
