### ISSUE TITLE
ValueError: in_channels must be divisible by groups

### ISSUE THREAD

**Issue by PkuRainBow** [mapillary/inplace_abn#21]
Hi, 

I want to train the deeplabv3 based on the ResNext model. But when I try to run the script, it informs that the errors like:

![image](https://user-images.githubusercontent.com/4639578/38600531-08aa9d32-3d97-11e8-888c-0cda95498697.png)

I check the code find groups=64 by default.
could you help me?
Thanks

##################################################

Besides, I am also wondering one small problem. It seems the performance using the ResNext trained with InplaceABNSync performs worse than the ResNext trained with InplaceABN.  Why could this happen?

**Comment by rotabulo** [comment]
@PkuRainBow Each grouped convolution requires the numer of groups to divide `inchannels`. Apparently, you create an `IdentityResidualBlock' object in your 'psp_resnext' script where this condition is violated.

As for sync vs non-sync, take into account that by using synchronized ABN your gradient estimation has a smaller variance, which has an implicit effect on the step size. In other terms, you might want to use a different learning rate. We always kept the same learning rate in our experiments and we experienced cases where with sync the performance improved and cases where there was little difference.

**Comment by PkuRainBow** [comment]
@rotabulo Yeah. I still have not figured out the first problem. 

As i use the default parameters to create the ResNext.

 `model = ResNeXt([3, 4, 23, 3], num_classes)`

And the codes for the ResNext just follow exactly the code you provide like below,

```
        # Groups of residual blocks
        in_channels = 64
        channels = base_channels
        for mod_id, num in enumerate(structure):
            # Create blocks for module
            blocks = []
            for block_id in range(num):
                s, d = self._stride_dilation(mod_id, block_id, dilation)
                blocks.append((
                    "block%d" % (block_id + 1),
                    IdentityResidualBlock(in_channels, channels, stride=s, groups=groups, dilation=d)
                ))

                # Update channels
                in_channels = channels[-1]

            # Create and add module
            self.add_module("mod%d" % (mod_id + 2), nn.Sequential(OrderedDict(blocks)))
            channels = [c * 2 for c in channels]
```
