### ISSUE TITLE
_backend.statistics(x):cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by Mrdongsonny** [mapillary/inplace_abn#213]
When the program executes at this line:  mean, var, count = _backend.statistics(x) of function.py , about at line86
 TypeError: cannot unpack non-iterable NoneType object
i set res = _backend.statistics(x), the value of res is none, and the x is not empty. is there anyone had same problem with me and had solved
Thanks u very mach for u reply

**Comment by Mrdongsonny** [comment]
i have solved this problem, we need put the script( train.py) to the sub folder of inplace_abn

**Comment by adaxidedakaonang** [comment]
How did you solve it? I met the same problem

**Comment by Q1ngS0ng** [comment]
How did you solve it? I met the same problem

> _No description provided._

**Comment by yukkizhang** [comment]
I met the same problem, can you tell me how you solved it？
