### ISSUE TITLE
About wider_resnet38_a2

### ISSUE THREAD

**Issue by Paranoidv** [mapillary/inplace_abn#22]
Hi, Thank you for yor good work , en , I want to ask you that , have you train WiderResNetA2 with ImageNet dataset? if you have , can you share the trained model ? Thank you!!!!!!!!!

**Comment by ducksoup** [comment]
Hi @Paranoidv , unfortunately we don't have a WiderResNetA2 model trained on ImageNet. However, you can safely use the WiderResNet weights we provide to initialize WiderResNetA2: this will still produce decent results, which can be further improved by running a couple epochs of fine-tuning on ImageNet.
