### ISSUE TITLE
cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by Q1ngS0ng** [mapillary/inplace_abn#235]
mean, var, count = _backend.statistics(x)
TypeError: cannot unpack non-iterable NoneType object

anyone could tell me how to fix it?

**Comment by Q1ngS0ng** [comment]
what do you want to do with _backend.cpython-38-x86_64-linux-gnu.so? I noticed that this file would be replaced by _backend.py, but the help_functions in backend.py is empty!

**Comment by adaxidedakaonang** [comment]
Same problem.

**Comment by yukkizhang** [comment]
I met the same problem, can you tell me how you solved it？

**Comment by Jarvis-zyq** [comment]
Same problem.

**Comment by kongsemancheng** [comment]
Same problem!
