### ISSUE TITLE
About the class reweighting method

### ISSUE THREAD

**Issue by PkuRainBow** [mapillary/inplace_abn#24]
Hi, I noticed that in the Table 2 of the paper of 

> The Mapillary Vistas Dataset for Semantic Understanding of Street Scenes

It mentions that with class reweighting, we can get about 1.3 points improvements. Could you show me how do to compute your class-aware weights?

I have tried other similar strategy but only get about 0.5 improvements.

**Comment by rotabulo** [comment]
@PkuRainBow you should ask the authors of PSPNet, since we are just reporting the results that they obtained on the LSUN'17 segmentation challenge.
