### ISSUE TITLE
 error: An extended __device__ lambda must not be defined in a function that is defined within another function

### ISSUE THREAD

**Issue by PkuRainBow** [mapillary/inplace_abn#26]
Hi, I find that you have updated your repo and I download the new repo.

I try to build the repo under such enviroments:

```
Ubuntu 16.04(docker)
Miniconda env: pytorch04
python: 3.6.5
cuda: 8.0
cudnn: 7.0
```
I meet such errors:
![image](https://user-images.githubusercontent.com/4639578/41041829-be55a2f0-69d2-11e8-93b7-b1af7f46c4b4.png)

**Comment by PkuRainBow** [comment]
@ducksoup

**Comment by fgtoralesch** [comment]
I had a similar issue, and in my case it was related to not finding cuda in "/usr/local/cuda" path. I solved it creating a symbolic link to my cuda path. Hope it helps.

**Comment by PkuRainBow** [comment]
@fbertetto Thanks, could you show me the exact operation to solve this problem?  As I can excute "nvcc" successfully.

**Comment by lizleo** [comment]
@PkuRainBow 
Hello , have you fixed this problem?

**Comment by PkuRainBow** [comment]
In fact, I have not solved this problem currently. @ducksoup  Ask for help~

**Comment by rotabulo** [comment]
@PkuRainBow did you re-compile the cuda code with `python setup.py install` ?

**Comment by PkuRainBow** [comment]
@rotabulo Yeah. I just create a new enviroment with conda and install the pytorch v0.4.

Then I download your current repo and recompile the cuda code with  **python setup.py install **

The reported exact errors still exist.

**Comment by ducksoup** [comment]
@PkuRainBow after a bit of googling I found out that your problem is related to the CUDA version: the way we use `__device__` lambda functions is only supported from CUDA 9.0 onward.

**Comment by PkuRainBow** [comment]
@ducksoup Thanks for your help! I will try the cuda9.0.

**Comment by ducksoup** [comment]
@PkuRainBow I just uploaded a small patch that should fix CUDA 8.0 compatibility, can you test with the latest commit in the `pytorch_v0.4` branch?

**Comment by PkuRainBow** [comment]
@ducksoup I will test it now and report the results later.

**Comment by lizleo** [comment]
@PkuRainBow cuda 9 works, and thanks for your help~
