### ISSUE TITLE
build problems

### ISSUE THREAD

**Issue by lxtGH** [mapillary/inplace_abn#27]
modules/src/inplace_abn_cuda.cu:192:21: error: macro "AT_ASSERT" passed 2 arguments, but takes just 1
modules/src/inplace_abn_cuda.cu:193:19: error: macro "AT_ASSERT" passed 2 arguments, but takes just 1
   CHECK_INPUT(bias);
                   ^
modules/src/inplace_abn_cuda.cu:193:19: error: macro "AT_ASSERT" passed 2 arguments, but takes just 1
modules/src/inplace_abn_cuda.cu:257:16: error: macro "AT_ASSERT" passed 2 arguments, but takes just 1
   CHECK_INPUT(z);
                ^
modules/src/inplace_abn_cuda.cu:257:16: error: macro "AT_ASSERT" passed 2 arguments, but takes just 1
modules/src/inplace_abn_cuda.cu:258:17: error: macro "AT_ASSERT" passed 2 arguments, but takes just 1
   CHECK_INPUT(dz);
                 ^
modules/src/inplace_abn_cuda.cu:258:17: error: macro "AT_ASSERT" passed 2 arguments, but takes just 1
modules/src/inplace_abn_cuda.cu:259:18: error: macro "AT_ASSERT" passed 2 arguments, but takes just 1
   CHECK_INPUT(var);
                  ^
modules/src/inplace_abn_cuda.cu:259:18: error: macro "AT_ASSERT" passed 2 arguments, but takes just 1
modules/src/inplace_abn_cuda.cu:260:21: error: macro "AT_ASSERT" passed 2 arguments, but takes just 1
   CHECK_INPUT(weight);
                     ^
modules/src/inplace_abn_cuda.cu:260:21: error: macro "AT_ASSERT" passed 2 arguments, but takes just 1
modules/src/inplace_abn_cuda.cu:261:19: error: macro "AT_ASSERT" passed 2 arguments, but takes just 1
   CHECK_INPUT(bias);
                   ^
modules/src/inplace_abn_cuda.cu:261:19: error: macro "AT_ASSERT" passed 2 arguments, but takes just 1
modules/src/inplace_abn_cuda.cu:262:18: error: macro "AT_ASSERT" passed 2 arguments, but takes just 1
   CHECK_INPUT(edz);
                  ^
modules/src/inplace_abn_cuda.cu:262:18: error: macro "AT_ASSERT" passed 2 arguments, but takes just 1
modules/src/inplace_abn_cuda.cu:263:19: error: macro "AT_ASSERT" passed 2 arguments, but takes just 1
   CHECK_INPUT(eydz);
                   ^
modules/src/inplace_abn_cuda.cu:263:19: error: macro "AT_ASSERT" passed 2 arguments, but takes just 1
modules/src/inplace_abn_cuda.cu:299:16: error: macro "AT_ASSERT" passed 2 arguments, but takes just 1
   CHECK_INPUT(z);
                ^
modules/src/inplace_abn_cuda.cu:299:16: error: macro "AT_ASSERT" passed 2 arguments, but takes just 1
modules/src/inplace_abn_cuda.cu:300:17: error: macro "AT_ASSERT" passed 2 arguments, but takes just 1
   CHECK_INPUT(dz);
                 ^
modules/src/inplace_abn_cuda.cu:300:17: error: macro "AT_ASSERT" passed 2 arguments, but takes just 1
modules/src/inplace_abn_cuda.cu:319:16: error: macro "AT_ASSERT" passed 2 arguments, but takes just 1
   CHECK_INPUT(z);
                ^
modules/src/inplace_abn_cuda.cu:319:16: error: macro "AT_ASSERT" passed 2 arguments, but takes just 1
modules/src/inplace_abn_cuda.cu:320:17: error: macro "AT_ASSERT" passed 2 arguments, but takes just 1
   CHECK_INPUT(dz);
                 ^
modules/src/inplace_abn_cuda.cu:320:17: error: macro "AT_ASSERT" passed 2 arguments, but takes just 1
error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1
Hi, when I install the repo, I met such error 
my environment is python3.6 , pytorch.0.5, cuda 9.0

**Comment by lizleo** [comment]
hi @pkontschieder 
I met an error as follows:

running install
running bdist_egg
running egg_info
writing top-level names to inplace_abn.egg-info/top_level.txt
writing inplace_abn.egg-info/PKG-INFO
writing dependency_links to inplace_abn.egg-info/dependency_links.txt
reading manifest file 'inplace_abn.egg-info/SOURCES.txt'
writing manifest file 'inplace_abn.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
building 'inplace_abn' extension
gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/leo/anaconda3/lib/python3.5/site-packages/torch/lib/include -I/home/leo/anaconda3/lib/python3.5/site-packages/torch/lib/include/TH -I/home/leo/anaconda3/lib/python3.5/site-packages/torch/lib/include/THC -I/usr/local/cuda/include -I/home/leo/anaconda3/include/python3.5m -c modules/src/inplace_abn.cpp -o build/temp.linux-x86_64-3.5/modules/src/inplace_abn.o -DTORCH_EXTENSION_NAME=inplace_abn -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/leo/anaconda3/lib/python3.5/site-packages/torch/lib/include -I/home/leo/anaconda3/lib/python3.5/site-packages/torch/lib/include/TH -I/home/leo/anaconda3/lib/python3.5/site-packages/torch/lib/include/THC -I/usr/local/cuda/include -I/home/leo/anaconda3/include/python3.5m -c modules/src/inplace_abn_cpu.cpp -o build/temp.linux-x86_64-3.5/modules/src/inplace_abn_cpu.o -DTORCH_EXTENSION_NAME=inplace_abn -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
/usr/local/cuda/bin/nvcc -I/home/leo/anaconda3/lib/python3.5/site-packages/torch/lib/include -I/home/leo/anaconda3/lib/python3.5/site-packages/torch/lib/include/TH -I/home/leo/anaconda3/lib/python3.5/site-packages/torch/lib/include/THC -I/usr/local/cuda/include -I/home/leo/anaconda3/include/python3.5m -c modules/src/inplace_abn_cuda.cu -o build/temp.linux-x86_64-3.5/modules/src/inplace_abn_cuda.o --expt-extended-lambda -DTORCH_EXTENSION_NAME=inplace_abn --compiler-options '-fPIC' -std=c++11
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
modules/src/inplace_abn_cuda.cu(304): error: An extended __device__ lambda must not be defined in a function that is defined within another function

modules/src/inplace_abn_cuda.cu(304): error: An extended __device__ lambda cannot be defined within a member function of a class that is unnamed

modules/src/inplace_abn_cuda.cu(304): error: An extended __device__ lambda must not be defined in a function that is defined within another function

modules/src/inplace_abn_cuda.cu(304): error: An extended __device__ lambda cannot be defined within a member function of a class that is unnamed

modules/src/inplace_abn_cuda.cu(304): error: An extended __device__ lambda must not be defined in a function that is defined within another function

modules/src/inplace_abn_cuda.cu(304): error: An extended __device__ lambda cannot be defined within a member function of a class that is unnamed

modules/src/inplace_abn_cuda.cu(304): error: An extended __device__ lambda must not be defined in a function that is defined within another function

modules/src/inplace_abn_cuda.cu(304): error: An extended __device__ lambda cannot be defined within a member function of a class that is unnamed

modules/src/inplace_abn_cuda.cu(304): error: An extended __device__ lambda must not be defined in a function that is defined within another function

modules/src/inplace_abn_cuda.cu(304): error: An extended __device__ lambda cannot be defined within a member function of a class that is unnamed

modules/src/inplace_abn_cuda.cu(304): error: An extended __device__ lambda must not be defined in a function that is defined within another function

modules/src/inplace_abn_cuda.cu(304): error: An extended __device__ lambda cannot be defined within a member function of a class that is unnamed

modules/src/inplace_abn_cuda.cu(304): error: An extended __device__ lambda must not be defined in a function that is defined within another function

modules/src/inplace_abn_cuda.cu(304): error: An extended __device__ lambda cannot be defined within a member function of a class that is unnamed

modules/src/inplace_abn_cuda.cu(304): error: An extended __device__ lambda must not be defined in a function that is defined within another function

modules/src/inplace_abn_cuda.cu(304): error: An extended __device__ lambda cannot be defined within a member function of a class that is unnamed

modules/src/inplace_abn_cuda.cu(324): error: An extended __device__ lambda must not be defined in a function that is defined within another function

modules/src/inplace_abn_cuda.cu(324): error: An extended __device__ lambda cannot be defined within a member function of a class that is unnamed

modules/src/inplace_abn_cuda.cu(324): error: An extended __device__ lambda must not be defined in a function that is defined within another function

modules/src/inplace_abn_cuda.cu(324): error: An extended __device__ lambda cannot be defined within a member function of a class that is unnamed

modules/src/inplace_abn_cuda.cu(324): error: An extended __device__ lambda must not be defined in a function that is defined within another function

modules/src/inplace_abn_cuda.cu(324): error: An extended __device__ lambda cannot be defined within a member function of a class that is unnamed

modules/src/inplace_abn_cuda.cu(324): error: An extended __device__ lambda must not be defined in a function that is defined within another function

modules/src/inplace_abn_cuda.cu(324): error: An extended __device__ lambda cannot be defined within a member function of a class that is unnamed

modules/src/inplace_abn_cuda.cu(324): error: An extended __device__ lambda must not be defined in a function that is defined within another function

modules/src/inplace_abn_cuda.cu(324): error: An extended __device__ lambda cannot be defined within a member function of a class that is unnamed

modules/src/inplace_abn_cuda.cu(324): error: An extended __device__ lambda must not be defined in a function that is defined within another function

modules/src/inplace_abn_cuda.cu(324): error: An extended __device__ lambda cannot be defined within a member function of a class that is unnamed

modules/src/inplace_abn_cuda.cu(324): error: An extended __device__ lambda must not be defined in a function that is defined within another function

modules/src/inplace_abn_cuda.cu(324): error: An extended __device__ lambda cannot be defined within a member function of a class that is unnamed

modules/src/inplace_abn_cuda.cu(324): error: An extended __device__ lambda must not be defined in a function that is defined within another function

modules/src/inplace_abn_cuda.cu(324): error: An extended __device__ lambda cannot be defined within a member function of a class that is unnamed

32 errors detected in the compilation of "/tmp/tmpxft_000051cc_00000000-7_inplace_abn_cuda.cpp1.ii".
error: command '/usr/local/cuda/bin/nvcc' failed with exit status 2

my environment is python3.5 , pytorch.0.4, cuda 8.0 cudnn 7.0.5
Could you please give me a hand?
thanks~

**Comment by rotabulo** [comment]
@lxtGH can you try with cuda 9 ?

**Comment by ducksoup** [comment]
@lizleo a patch that should fix CUDA 8.0 compatibility has just been added to the `pytorch_v0.4`. Can you test if this fixes your issue and get back to us?

**Comment by lizleo** [comment]
@rotabulo cuda 9.0 works, thanks a lot~

**Comment by rotabulo** [comment]
@lizleo welcome, I close the issue
