### ISSUE TITLE
When could you release the codes on Mapillary dataset?

### ISSUE THREAD

**Issue by PkuRainBow** [mapillary/inplace_abn#29]
Really great repo.

I am wondering when would it be convenient for you to opensource the codes on Mapillary dataset?

We want to conduct some experiments based on your baseline.

**Comment by pkontschieder** [comment]
We have just released model and inference code for our #1 ranked Mapillary Vistas Semantic Segmentation model.

**Comment by eugenelawrence** [comment]
Hi, @pkontschieder 
Will you release the code on Cityscapes?
