### ISSUE TITLE
invalid device function

### ISSUE THREAD

**Issue by iliadsouti** [mapillary/inplace_abn#3]
I got an error on using both 'elu' and 'leakyrelu' activation :  
File "/home/ubuntu/projects/inplace_abn/modules/functions.py", line 43, in _act_forward
    _ext.elu_cuda(x)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 180, in safe_call
    result = torch._C._safe_call(*args, **kwargs)
**torch.FatalError: function_attributes(): after cudaFuncGetAttributes: invalid device function**

**Comment by ducksoup** [comment]
Are you using a Kepler GPU (e.g. K40 / K80)? If so, you should change the GPU architectures in  `modules/build.sh` before compiling the CUDA code, as the provided defaults or for Maxwell and Pascal GPUs (e.g. Titan X / Xp).

For Kepler cards, the correct setting is:
```
CUDA_GENCODE="\
-gencode=arch=compute_35,code=sm_35 \
-gencode=arch=compute_30,code=sm_30"
```

**Comment by irfanICMLL** [comment]
Helllo！ I use a v100GPU, and I got the same error using both settings as

**Comment by ducksoup** [comment]
@irfanICMLL The correct settings for V100 GPUs (i.e. Nvidia Volta architectures) are:

```
CUDA_GENCODE="-gencode=arch=compute_70,code=sm_70"
```
