### ISSUE TITLE
class uniform sampling

### ISSUE THREAD

**Issue by ternaus** [mapillary/inplace_abn#31]
In http://openaccess.thecvf.com/content_cvpr_2018/papers/Bulo_In-Place_Activated_BatchNorm_CVPR_2018_paper.pdf

you say:
```
For CLASS-UNIFORM SAMPLING, we compiled the minibatches per epoch in a way to show all classes uniformly instead of randomly perturbing the dataset (thus following an oversampling strategy for underrepresented categories).
```

How exactly do you perform this on a Vistas Dataset, where each image has from 1 to 66 classes?

**Comment by ternaus** [comment]
Am I right?

1. You pick one out of 65 classes randomly uniformly.
2. Randomly choose an image that contains this class?

**Comment by rotabulo** [comment]
@ternaus yes. To be more precise, since we crop the image, we ensure that the crop contains at least one pixel of the sampled class.

**Comment by ternaus** [comment]
Do you repeat RandomCrop till you ensure that target class pixel exists on the image?

**Comment by rotabulo** [comment]
No, we just randomly pick a pixel of the target class from the image and sample a crop that contains it.

**Comment by ternaus** [comment]
Thank you!
