### ISSUE TITLE
SIGSEGV for CUDA8.0

### ISSUE THREAD

**Issue by ansleliu** [mapillary/inplace_abn#34]
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

**Comment by rotabulo** [comment]
@ansleliu can you provide us with more information? Also we stopped supporting cuda 8. Could you try with a more recent version of cuda?

**Comment by ansleliu** [comment]
@rotabulo Thank you for your rapid reply, I have solved this problem by updating the GCC from 4.8  to the latest version (because PyTorch "cpp_extensions" requires GCC 4.9 or higher) and so it is not caused by CUDA. Ref. hier bitte: [https://github.com/pytorch/pytorch/issues/6987](url), Thanks.
