### ISSUE TITLE
WideResNet38, InPlace-ABN weights

### ISSUE THREAD

**Issue by alexdonchuk** [mapillary/inplace_abn#41]
Hi! Looks like weight file corrupt. Can you upload it again?

**Comment by rotabulo** [comment]
@alexdonchuk we downloaded the file again and checked the md5 sum and it matches, so we don't see issues with the uploaded file. Can you be more specific about the issue?

**Comment by rotabulo** [comment]
@alexdonchuk you should open the file with `torch.load`.

**Comment by alexdonchuk** [comment]
@rotabulo oh! Sorry and thank you.
