### ISSUE TITLE
Labels for the semantic segmentation

### ISSUE THREAD

**Issue by talsperre** [mapillary/inplace_abn#42]
Thanks for uploading the pre-trained model for semantic segmentation. I was using the model for inference purposes and wanted to know the labels for the semantic segmentation outputs corresponding to the argument ```palette``` in ```output-mode```. They seem to be different from the Cityscapes labels.

**Comment by rotabulo** [comment]
@talsperre they correspond to the labels of the Mapillary Vistas dataset.

**Comment by rotabulo** [comment]
I close the issue.
