### ISSUE TITLE
'unexpected key "mod2.block1.bn1.bn.weight" in state_dict'

### ISSUE THREAD

**Issue by PkuRainBow** [mapillary/inplace_abn#45]
Hi, I want to employ the WideResNet38, InPlace-ABN for scene parsing task.

I just make some modifications, firstly I add this line to ensure the ABN is set right,

```
from modules import InPlaceABNSync
ABN = functools.partial(InPlaceABNSync)
```

Then we load the parameters like this,

```
       deeplab = get_segmentation_model(args.method, num_classes=args.num_classes)
       #args.restore_from =  './pretrain_model/wide_resnet38_ipabn_lr_256.pth.tar'
        saved_state_dict = torch.load(args.restore_from)
        saved_state_dict = saved_state_dict['state_dict']
        new_params = deeplab.state_dict().copy()
        for i in saved_state_dict:
            i_parts = i.split('.')
            if not i_parts[1]=='classifier':
                new_params['.'.join(i_parts[1:])] = saved_state_dict[i]
```

We excute  the  **print(new_params['mod2.block1.bn1.bn.weight'])** and get the right output.

Thus we have loaded the pretrained parameters in to the array new_params.

Then we excute ,

` deeplab.load_state_dict(new_params)`

It just informed me that 

> 'unexpected key "mod2.block1.bn1.bn.weight" in state_dict'

This is a little strange for me as I have checked that the parameters have been loaded successfully to the  new_params.

**Comment by rotabulo** [comment]
@PkuRainBow print the parameters' names of `deeplab` so maybe you figure out why the keys you provide are wrong.

**Comment by PkuRainBow** [comment]
@rotabulo I print the parameters' name of deeplab and find that there exist no key with name  **'mod2.block1.bn1.bn.weight'**

But the check point you provide contains the parameter with key name both **'mod2.block1.bn1.weight'** and **'mod2.block1.bn1.bn.weight'**.

So I am wondering whether it is related to the problem of your checkpoint?

**Comment by rotabulo** [comment]
@PkuRainBow I checked the checkpoint files and they are correct, i.e. the key you mention is not there. I suspect you are using an older version of the checkpoint.

**Comment by PkuRainBow** [comment]
@rotabulo Thanks!  I have solved this problem by using the new checkpoint.
