### ISSUE TITLE
What is the difference between the current InPlaceABNSync and the previous version.

### ISSUE THREAD

**Issue by PkuRainBow** [mapillary/inplace_abn#47]
Hi, I used to implement my segmentation system based on the earliest version of the InplaceABNSync and achieve good performance. (based on pytorch0.3)

Recently, I have tried to employ the newest version of the InplaceABNSync under pytorch0.4 and find the performance drops about 1 point mIou.

In fact, I have checked all my implementations for multiple times and find the only possible reason for the performance gap is related to the provided InplaceABNSync as I follow the same manner to use the current InplaceABNSync as the previous version.

Could you give me some advice the possible changes that I need to adopt?

**Comment by rotabulo** [comment]
@PkuRainBow are you testing with the new code on a model trained with the old version?

**Comment by PkuRainBow** [comment]
@rotabulo No, I retrain the model with the new version.

**Comment by PkuRainBow** [comment]
@rotabulo I am wondering whether you choose pytorch0.4.0 or 0.4.1. 

I hear that there exist bugs with the 0.4.0 for the BN setup.

**Comment by rotabulo** [comment]
@PkuRainBow our inplace ABN does not depend on BN implementations from pytorch. We tested on both pytorch 0.4 and 0.4.1. . Is it possible that there were other changes in Pytorch that triggered the reduced performance?

**Comment by rotabulo** [comment]
@PkuRainBow we have in the meanwhile released a new version of our code that requires PyTorch v1.0 and supports multi-process synchronization. I am closing the issue.
