### ISSUE TITLE
conflict between inplaceABNSync and torch.utils.checkpoint

### ISSUE THREAD

**Issue by lfz** [mapillary/inplace_abn#48]
Hi, I tried to further reduce the memory usage by using torch.utils.checkpoint. But when I use it along with inplaceABNSync, the training will be stuck after several iterations.

It turns out that the master_queue in backward doesn't get anything. When I use inplaceABN, everything works fine.

In your paper you mentioned that you implemented a checkpoint method, have you tried to combine checkpoint and inplace_abn_sync? Thank you ~

Here is the bug report, I added a timeout para to reveal the bug

 File "/home/data/alg-coronary-seg3d/models/inplace_abn/functions.py", line 219, in backward

    edz_w, eydz_w = ctx.master_queue.get(timeout=5)

  File "/root/anaconda3/lib/python3.6/queue.py", line 172, in get

    raise Empty

queue.Empty

**Comment by ducksoup** [comment]
We never tested our code together with Pytorch's checkpointing. In general, our synchronized BN relies on the assumption that all GPUs are always computing the same modules at the same time, which is probably violated by checkpointing. Unfortunately, modifying our implementation to overcome this limitation is quite cumbersome and would probably require some modifications to Pytorch's internals.
