### ISSUE TITLE
Running too slowly

### ISSUE THREAD

**Issue by Walstruzz** [mapillary/inplace_abn#51]
Hi, thank you for your wonderful work!

I tried to use it to finish my semantic segmentation task. I do:

- **`sudo apt-get install ninja-build`**

- **`git clone https://github.com/mapillary/inplace_abn.git`**

- **`cd inplace-abn`**

- **`CUDA_VISIBLE_DEVICES=3 python test_vistas.py ./wide_resnet38_deeplab_vistas.pth.tar ./data/input/ ./data/output/`**

The segmentation results are well. But it costs about 12 seconds for per input picture. Is there something wrong with my operations? Or any parameter I could set to fix this problem?

System: Ubuntu 16.04 LTS
Images(jpg) size: 360(w) * 240(h)
Device: NVIDIA GTX 1080ti with 11GB RAM
Driver version 384.81
CUDA: 9.0
PyTorch: 0.4.0
NVCC Compiler, GCC, G++: 4.8.5

**Comment by rotabulo** [comment]
@Walstruzz I don't have a Titan 1080Ti at hand to try, but take into account that the script resizes the longest dimension to 2048 and applies scale augmentation after that with 3 scales. In your case within the 12 seconds, the script performs 3 forward passes at resolutions 1365x2048, 955x1433, 1638x2458 + fusion at 1365x2048 + downsampling at the original size + loading and saving.
Also, if this is not the case, you should measure the timing over multiple images, and not just 1.

**Comment by Walstruzz** [comment]
@rotabulo 
Sorry, maybe I didn't express it clearly. I had measured the timing over multiple images and it took an average of 12 seconds.
As you said, the script resizes the longest dimension to 2048. I change the script _test_vistas_single_gpu.py_

**`transformation = SegmentationTransform(
        2048,
        (0.41738699, 0.45732192, 0.46886091),
        (0.25685097, 0.26509955, 0.29067996),
    )`**

to 

**`transformation = SegmentationTransform(
        1024,
        (0.41738699, 0.45732192, 0.46886091),
        (0.25685097, 0.26509955, 0.29067996),
    )`**

and now it runs faster.
Thank you very much!!!
