### ISSUE TITLE
When I use InplaceSyncBn, it runs very slowly.

### ISSUE THREAD

**Issue by ycszen** [mapillary/inplace_abn#57]
`GPU benchmark: 8 x 1080 Ti`
`Cuda version: 9.0`
`Pytorch version: 0.4.1` 
`GCC version: 5.4.0`

I copy the `modules` of this repo into my lib, and then I use this code snippet 
`from seg_opr.inplace_abn import InPlaceABNSync`
`InPlaceSyncBatchNorm2d = functools.partial(InPlaceABNSync, activation='none')`.
However, the experiment runs very slow, even 90s per iteration. When I use other sync bn or official bn, the code is normal while the speed is 1.19s per iteration.
My experiment config:
`batch size: 16`
`num workers: 16`
`input size: 480x480`
 Could you give me any advice or explanation?

**Comment by rotabulo** [comment]
@ycszen we have released today a new version of our code that requires PyTorch v1.0 and supports multi-process synchronization. This solves problems with training on more than 4 Gpus.

**Comment by rotabulo** [comment]
Closing because the new version should have solved the issue.
