### ISSUE TITLE
problem about torch.utils.checkpoint with InplaceABNSync

### ISSUE THREAD

**Issue by JamesKasperYu** [mapillary/inplace_abn#60]
Hi,I want to use torch.utils.checkpoint with InplaceABNSync to divid the net to 4 parts to train,the GPU keeps the memory but don't work in torch.autograd.backward.I find that  only a gpu get the backward result and is waiting other gpus' result but other gups don't give any result out.No Sync works well.

**Comment by rotabulo** [comment]
@JamesKasperYu we have released a new version of our code that requires PyTorch v1.0 and supports multi-process synchronization. You can try with the new version, but I am not sure that synchronization and checkpoining will work out of the box without some tricks.
