### ISSUE TITLE
Compile error in pytorch 1.0

### ISSUE THREAD

**Issue by Towardsmoon** [mapillary/inplace_abn#61]
Cannot compile in pytorch 1.0.

**Comment by rotabulo** [comment]
@wobenwuliang we will make our code compatible once pytorch 1.0 becomes a stable release.

**Comment by rotabulo** [comment]
@Chetter2 thank you for providing a fix for those who want to switch to pytorch 1.0 immediately.

**Comment by antran89** [comment]
@Chetter2 Still have error in `inplace_abn_cuda.cu`.

**Comment by CS-Jackson** [comment]
Hi, @rotabulo , thanks for the great job. Can I used this code for the stable pytorch 1.0?

**Comment by rotabulo** [comment]
@Towardsmoon @Chetter2 @CS-Jackson we have released today a new version of the code that requires PyTorch v1.0 and supports multi-process synchronization.

**Comment by CoinCheung** [comment]
@rotabulo Hi, Thanks for your work. Here is a basic question: Shall I tuck your repository in pytorch repository and compile pytorch together with inplace bn, or shall I compile your repository independently from pytorch. How could I install your inplace bn please?

**Comment by rotabulo** [comment]
@CoinCheung after you have installed pytorch v1.0 and becomes visible from python, you can simply clone our repo and start any script there. Compilation will then be triggered automatically.
