### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 1879: ordinal not in range(128)

### ISSUE THREAD

**Issue by codermckee** [mapillary/inplace_abn#63]
My Environment are as followed:
python 2.7
torch 0.4.1
cuda 9.0

and I failed to run test_vistas.py, can someone help me?

**Comment by rotabulo** [comment]
@codermckee can you please provide more details about the exception?

**Comment by codermckee** [comment]
> @codermckee can you please provide more details about the exception?

I have solved this problem by switching to python 3. because the default encoding of python2.7 is ascii and python3 is utf-8.

But a new problem happpened. 
" ninja: build stopped: subcommand failed"

So sad.

**Comment by rotabulo** [comment]
@codermckee Please, provide more details about the new error.

**Comment by codermckee** [comment]
@rotabulo 
thanks for your reply. **Following is the details of my new error.**

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/cpp_extension.py", line 576, in _build_extension_module
    ['ninja', '-v'], stderr=subprocess.STDOUT, cwd=build_directory)
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_vistas_single_gpu.py", line 14, in <module>
    import models
  File "/home/mckee/inplace_abn/models/__init__.py", line 1, in <module>
    from .resnext import *
  File "/home/mckee/inplace_abn/models/resnext.py", line 8, in <module>
    from modules import IdentityResidualBlock, ABN, GlobalAvgPool2d
  File "/home/mckee/inplace_abn/modules/__init__.py", line 1, in <module>
    from .bn import ABN, InPlaceABN, InPlaceABNSync
  File "/home/mckee/inplace_abn/modules/bn.py", line 10, in <module>
    from .functions import *
  File "/home/mckee/inplace_abn/modules/functions.py", line 16, in <module>
    extra_cuda_cflags=["--expt-extended-lambda"])
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/cpp_extension.py", line 501, in load
    _build_extension_module(name, build_directory)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/cpp_extension.py", line 582, in _build_extension_module
    name, error.output.decode()))
RuntimeError: Error building extension 'inplace_abn': [1/2] /usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=inplace_abn -I/usr/local/lib/python3.5/dist-packages/torch/lib/include -I/usr/local/lib/python3.5/dist-packages/torch/lib/include/TH -I/usr/local/lib/python3.5/dist-packages/torch/lib/include/THC -I/usr/local/cuda/include -I/usr/include/python3.5m --compiler-options '-fPIC' --expt-extended-lambda -std=c++11 -c /home/mckee/inplace_abn/modules/src/inplace_abn_cuda.cu -o inplace_abn_cuda.cuda.o
FAILED: inplace_abn_cuda.cuda.o 
/usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=inplace_abn -I/usr/local/lib/python3.5/dist-packages/torch/lib/include -I/usr/local/lib/python3.5/dist-packages/torch/lib/include/TH -I/usr/local/lib/python3.5/dist-packages/torch/lib/include/THC -I/usr/local/cuda/include -I/usr/include/python3.5m --compiler-options '-fPIC' --expt-extended-lambda -std=c++11 -c /home/mckee/inplace_abn/modules/src/inplace_abn_cuda.cu -o inplace_abn_cuda.cuda.o
/home/mckee/inplace_abn/modules/src/inplace_abn_cuda.cu(99): error: class "at::Tensor" has no member "options"

/home/mckee/inplace_abn/modules/src/inplace_abn_cuda.cu(99): error: no instance of constructor "at::Type::Type" matches the argument list
            argument types are: (int64_t)

/home/mckee/inplace_abn/modules/src/inplace_abn_cuda.cu(100): error: class "at::Tensor" has no member "options"

/home/mckee/inplace_abn/modules/src/inplace_abn_cuda.cu(100): error: no instance of constructor "at::Type::Type" matches the argument list
            argument types are: (int64_t)

/home/mckee/inplace_abn/modules/src/inplace_abn_cuda.cu(202): error: class "at::Tensor" has no member "options"

/home/mckee/inplace_abn/modules/src/inplace_abn_cuda.cu(202): error: no instance of constructor "at::Type::Type" matches the argument list
            argument types are: (int64_t)

/home/mckee/inplace_abn/modules/src/inplace_abn_cuda.cu(203): error: class "at::Tensor" has no member "options"

/home/mckee/inplace_abn/modules/src/inplace_abn_cuda.cu(203): error: no instance of constructor "at::Type::Type" matches the argument list
            argument types are: (int64_t)

8 errors detected in the compilation of "/tmp/tmpxft_00005781_00000000-6_inplace_abn_cuda.cpp1.ii".
**ninja: build stopped: subcommand failed.**

**Comment by rotabulo** [comment]
@codermckee a relatively recent modification that we introduced relies on a more recent version of Aten. I suspect that your pre-compiled version of Pytorch uses an older version of Aten. The pre-compiled pytorch 0.4.1 with cuda 9.2 works for us. Can you try that one? Alternatively, you can try to compile pytorch yourself  so that a recent version Aten gets integrated.

**Comment by codermckee** [comment]
> @codermckee a relatively recent modification that we introduced relies on a more recent version of Aten. I suspect that your pre-compiled version of Pytorch uses an older version of Aten. The pre-compiled pytorch 0.4.1 with cuda 9.2 works for us. Can you try that one? Alternatively, you can try to compile pytorch yourself so that a recent version Aten gets integrated.

Thank you very much. I'll have a try later.

**Comment by rotabulo** [comment]
@codermckee in the meanwhile we have released a new version of our code that is compatible with PyTorch v1.0 and supports multi-process synchronization.
