### ISSUE TITLE
about the assumption that the count on every gpu is same

### ISSUE THREAD

**Issue by chenchr** [mapillary/inplace_abn#68]
Hello. Thanks for the awesome code.
In the code [here](https://github.com/mapillary/inplace_abn/blob/master/modules/functions.py#L152), 
```
 count = _count_samples(x) * (ctx.master_queue.maxsize + 1)
```
It seems that it assume that the count on every gpu is the same. However, for task like detection, which difference image may have different num of bounding box, it seems it will influence the result.
Maybe every work should sync the count as well as the mean and var, and then compute the overall mean and var using count on every gpu ?

**Comment by rotabulo** [comment]
@chenchr we have released a new version of our code that supports PyTorch v1.0 and multi-process synchronization. We have also added a flag in the layer to support different batch sizes per gpu, however note that there has to be at least one sample per gpu.

**Comment by chenchr** [comment]
Thanks you for the reply.
