### ISSUE TITLE
RunError

### ISSUE THREAD

**Issue by suyanzhou626** [mapillary/inplace_abn#69]
When I use InpalceABN, I encountered errors. My code is OK， I test it.

RuntimeError: invalid argument 3: divide by zero at /pytorch/aten/src/THC/generic/THCTensorMathPairwise.cu:88

**Comment by rotabulo** [comment]
@suyanzhou626 we need more information about the error.

**Comment by suyanzhou626** [comment]
@rotabulo I have encountered a new problem, you inplaceabnsync, when I use this layer, my program  can not run,like below picture, have been stuck in the model to infer, can't run out,  is there any precondition for using this layer? and how to slove it.
![image](https://user-images.githubusercontent.com/37359271/49445512-06f84f80-f80d-11e8-8c7e-806fad8d4549.png)

GPU: 4 * 1080Ti
CUDA: 9.0
pytorch: 0.41
GCC: 5.4

**Comment by rotabulo** [comment]
@suyanzhou626 we have released a new version of our code that supports PyTorch v1.0 and multi-process synchronization. Can you try with that?

**Comment by rotabulo** [comment]
I am closing the issue due to inactivity. Please re-open it if the problem persists with the new release.
