### ISSUE TITLE
Deterioration of convergence with Inplace-ABN

### ISSUE THREAD

**Issue by GolovanovSrg** [mapillary/inplace_abn#70]
When replacing BN with Inplace-ABN in the pre-trained model, there is a significant deterioration in convergence. Is this an expected behavior?

Also when using ELU, NAN sometimes appears. Adding eps to log1p corrects this situation.

**Comment by rotabulo** [comment]
@GolovanovSrg which pre-trained models do you refer to? BN does not have an embedded activation layer, whereas inplace-ABN does.

**Comment by GolovanovSrg** [comment]
I use SENet from https://github.com/Cadene/pretrained-models.pytorch. Replacing BN + Activation with Inplace-ABN allows easy use of available weights. But with further training convergence significantly deteriorates.

**Comment by GolovanovSrg** [comment]
@rotabulo I can not say anything about test, but when training, even without the pre-trained weights, the convergence is worse.

**Comment by rotabulo** [comment]
@GolovanovSrg we did not experience significant drops in performance by simply switching BN + Relu with Inplace-ABN + LeakyRELU. Regarding ELU, we haven't used it that much. Please note that we have a new release that supports PyTorch v1.0 and multi-process synchronization.

**Comment by rotabulo** [comment]
I am closing the issue. Please reopen it if you experience the same problems with the newer release.
