### ISSUE TITLE
The segmentation training script supporting multi-processing.

### ISSUE THREAD

**Issue by PkuRainBow** [mapillary/inplace_abn#75]
It is great to find that you support the multi-processing.

We are wondering whether you could share us the segmentation training script on Cityscapes or Mappillary dataset.

We also want to apply multi-processing to speed up the training.

**Comment by Maverick051293** [comment]
That would be great if we can get it. I've been trying to write it myself but it's not coming right! Lots of bugs!

**Comment by ducksoup** [comment]
In an effort to streamline the resolution process we are closing any issue not directly related with the InPlace-ABN _code and scripts_. Please use other channels if you need to contact us about our paper or the Mapillary Vistas dataset.
