### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by lcybuzz** [mapillary/inplace_abn#78]
Thanks for sharing the codes! I'm trying to apply ABN on my segmentation work. However, when moving the model to cuda by running `model.cuda()`, this error occurs:
>RuntimeError: CUDA out of memory. Tried to allocate 9.00 MiB (GPU 0; 22.38 GiB total capacity; 132.45 MiB already allocated; 11.88 MiB free; 309.00 KiB cached)

I successfully ran the old version which is compiled using `torch.utils.ffi`. I don't know if this error is  related to JIT compiling of PyTorch 1.0. 

Has anyone got any idea about this? Thanks a lot~

**Comment by loveddy** [comment]
hi, have you solved your problem?

**Comment by wutianyiRosun** [comment]
Hi, @lcybuzz ,@loveddy, have you solved this problem?

**Comment by lcybuzz** [comment]
@rotabulo I found the same issue using standard BN. Maybe it is not caused by the new version of ABN. Got no idea about this weird error :(

**Comment by rotabulo** [comment]
@lcybuzz I am closing the issue. I invite you to open an issue on PyTorch's github since the error message does not sound right and this is eventually a bug that does not depend on our code.

**Comment by bryanyzhu** [comment]
@lcybuzz @loveddy Hi, have you solved your problem? I met the same thing. I did `from modules import InPlaceABNSync`, but still OOM. Thank you very much.
