### ISSUE TITLE
RuntimeError: CUDA ouf memory.

### ISSUE THREAD

**Issue by wutianyiRosun** [mapillary/inplace_abn#80]
Hi, @mapillary-ci, it is great to find your work "inplace_abn". I meet some problem when I use your recently Pytorch 1.0 based inplace_abn package.

**RuntimeError: CUDA out of memory. Tried to allocate 36.88 MiB (GPU 0; 11.17 GiB total capacity; 3.29 GiB already allocated; 23.38 MiB free; 4.13 MiB cached)**

My system configuration is as follows:　
   PyTorch: v1.0.0, Cuda: v9.2, Cudnn: v7.2, Python3.6, Ubuntu 14.04, GCC: V5.4.1.
In addition, I can successfully import packages, such as "from modules import ABN". But I meet the above problem when I try to train my model. Could you give me some suggestion for solving this problem, thanks u very much!

**Comment by rotabulo** [comment]
@wutianyiRosun actually, if you are importing ABN, you are using standard batch norm, which implies that the error is not sue to our InplaceABN layer.

**Comment by rotabulo** [comment]
I am closing the issue, since it is apparently not related to our inplace ABN layer.

**Comment by bryanyzhu** [comment]
@wutianyiRosun @rotabulo Hi, have you solved your problem? I met the same thing. I did `from modules import InPlaceABNSync`, but still OOM. Thank you very much.
