### ISSUE TITLE
Training code for Mapillary dataset

### ISSUE THREAD

**Issue by robi56** [mapillary/inplace_abn#82]
There I have  found a script train_imagenet.py. If I want to train the inplace_abn model on Mapillary dataset, what should I do? It  would be helpful if there is a file look like train_vistas.py . :)

**Comment by ducksoup** [comment]
In an effort to streamline the resolution process we are closing any issue not directly related with the InPlace-ABN _code and scripts_. Please use other channels if you need to contact us about our paper or the Mapillary Vistas dataset.
