### ISSUE TITLE
Error importing module

### ISSUE THREAD

**Issue by patrickpoirson** [mapillary/inplace_abn#85]
from .wider_resnet import WiderResNetA2    
    from modules import IdentityResidualBlock, ABN, GlobalAvgPool2d
  File "./modules/__init__.py", line 1, in <module>
    from .bn import ABN, InPlaceABN, InPlaceABNSync
  File "./modules/bn.py", line 10, in <module>
    from .functions import *
  File "./modules/functions.py", line 18, in <module>
    extra_cuda_cflags=["--expt-extended-lambda"])
    return _import_module_from_library(name, build_directory, is_python_module)
    file, path, description = imp.find_module(module_name, [path])
        raise ImportError(_ERR_MSG.format(name), name=name)raise ImportError(_ERR_MSG.format(name), name=name)

ImportError: ImportErrorNo module named 'inplace_abn': 
No module named 'inplace_abn'

I am getting the following error when trying to import inplace_abn. The code works fine on my other machines but fails on the one with 1080 gpus.

Env settings:
Cuda 9.0
Pytorch 1.0.0 installed from conda
Gpus: 4x GTX 1080TI

**Comment by rotabulo** [comment]
@patrickpoirson it looks like the compilation failed. There are reported issues with cuda 9.0 and gcc, so it's better to use cuda 9.2. What is the configuration of the working machines?

**Comment by patrickpoirson** [comment]
Thanks for the help. All the machines have cuda 9.0 and gcc version 5.4.0.
