### ISSUE TITLE
Error when running with fp16 inputs

### ISSUE THREAD

**Issue by kampelmuehler** [mapillary/inplace_abn#86]
Hi,

I'm getting the following error when using `InPlaceABN` in an fp16 training pipeline:

```
[...]"functions.py", line 99, in forward
    running_mean.mul_((1 - ctx.momentum)).add_(ctx.momentum * mean)
RuntimeError: output with type torch.cuda.HalfTensor doesn't match the desired type torch.cuda.FloatTensor
```
any thoughts?

Thanks!

**Comment by rotabulo** [comment]
@kampelmuehler are you casting the module to half ? Otherwise the buffers stay fp32.

**Comment by kampelmuehler** [comment]
Yes, the whole module that's using InPlaceABN is cast to half precision.

the problem rises from line 96 in the same file:

`mean, var = _backend.mean_var(x)`

mean and var are returned as fp32 from the backend, which makes the subsequent `.add_()` operation fail.

**Comment by rotabulo** [comment]
@kampelmuehler we implemented the layer in a way to allow the possibility of having a fp16 input, but weights and buffers should stay fp32 to avoid numerical inaccuracies. Our implementation is not enabled yet to be used in a full fp16 mode.

**Comment by kampelmuehler** [comment]
alright, thanks for clarification!

**Comment by rotabulo** [comment]
@kampelmuehler I am closing the issue, but I will put a comment in the README to avoid future misunderstandings. Thanks for pointing it out.
