### ISSUE TITLE
Can't install with pip install

### ISSUE THREAD

**Issue by Jayan-K-Duggal** [mapillary/inplace_abn#87]
I got this error :

FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-vr5iy1dr/setup.py'

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-2cpaoznm/
And I think steup.py file is missing too

**Comment by rotabulo** [comment]
@JK009 we do not support direct installation via pip. Could you provide more details about the way you are trying to install?

**Comment by JK009** [comment]
I am following this link:
https://medium.com/@eugenekhvedchenya/why-you-should-start-using-in-place-activated-batchnorm-11a85bb15c06

and trying to install using pip : pip install git+https://github.com/mapillary/inplace_abn

I downloaded the repo but wasn't able to use it with nn model, please let me know how can I use batch normalization in place instead of batch norm2d.

**Comment by rotabulo** [comment]
@Jayan-K-Duggal you should clone the repo and add it to python's search path.

**Comment by Jayan-K-Duggal** [comment]
I cloned it and added to my python path but I want to use this with squeezenext model but in python or pytorch 1.0

**Comment by amaanda** [comment]
@Jayan-K-Duggal were you able to solve the problem? I also tried downloading, added it to the path and it still won't work.

**Comment by Jayan-K-Duggal** [comment]
@amaanda No, I give me some other kind of error, I don't remember exactly, will eventually mention it down when I will rerun the model. The ABN still is not working with my custom made NN model.

**Comment by amaanda** [comment]
@Jayan-K-Duggal alright, please share when possible so we can try to solve it. I am now trying to convert the model from pytorch to tensorflow, but there seems to be a problem with how torch saves the model.

**Comment by ducksoup** [comment]
Since version `1.0.0` it's possible to install the InPlace-ABN library directly from pip with: `pip install git+https://github.com/mapillary/inplace_abn.git`.
