### ISSUE TITLE
Training for KITTI dataset

### ISSUE THREAD

**Issue by sabrinazuraimi** [mapillary/inplace_abn#90]
Hi, I found this project through the KITTI project page which listed your method as #1 for their pixel-level semantic segmentation tasks. However, I could only find the codes for training_imagenet.py here, how do I test this for the KITTI dataset? Should I modify the training_imagenet.py script to somehow work with KITTI?

**Comment by AmeetR** [comment]
Following. Would also want the answer to this (and other custom datasets). rn I'm thinking about just modifying the imagenet code to work, but I'm not sure how easy that would be. Maybe it would be easier just to write our own code using the model.py files.

**Comment by ducksoup** [comment]
In an effort to streamline the resolution process we are closing any issue not directly related with the InPlace-ABN _library and scripts_. Please use other channels if you need to contact us about our paper or the Mapillary Vistas dataset.
