### ISSUE TITLE
Difference between InPlaceABN and ABN

### ISSUE THREAD

**Issue by Chetter2** [mapillary/inplace_abn#92]
During conversion of a trained model, I found a difference in the implementation of InPlaceABN and ABN. Problem arises due to taking absolute value of weight in affine operation, which is not used by functional.batch_norm in ABN.

Minimal code to reproduce
```python
abn = ABN(100, affine=True)
ipabn = InPlaceABN(100, affine=True)
abn.weight = nn.Parameter(-torch.ones(100))
ipabn.weight = abn.weight
abn.cuda()
ipabn.cuda()
inp = torch.rand((10, 100, 3, 3)).cuda()
abn_out = abn(inp)
ipabn_out = ipabn(inp)
torch.abs(abn_out - ipabn_out).max()
```

https://github.com/mapillary/inplace_abn/blob/42b09524b1bce788e7bcc190a55a6f020895fba8/modules/src/inplace_abn_cuda.cu#L114

**Comment by rotabulo** [comment]
@Chetter2 thank you for pointing this out. We introduced it in order to avoid division by zero and the change does not harm training compared to having the standard linear form. 
It prevents nevertheless the possibility of loading directly models that were trained with standard bn in case they exhibit negative scaling factors. However, there are ways of pre-processing the pre-trained weights to overcome the incompatibility issue

**Comment by Chetter2** [comment]
Thank you for your prompt response.
I had an opposite problem when I tried to replace InPlaceABN with ABN (in order to use jit and deploy). I am already taken absolute values of weights and added epsilon to it. Now ABN works like a charm. But this behavior was quite unexpected.

**Comment by ducksoup** [comment]
ABN is intended as a replacement of Pyotrch's standard BN + activation function, and not as a non-inplace version of InPlaceABN. Since the naming might understandably generate confusion I'll update the ABN docstrings to highlight this.

**Comment by bonlime** [comment]
For anyone interested in exporting models trained with InPlaceABN: 
This code fixed the difference
```python
from inplace_abn import ABN, InPlaceABN
import torch
def patch_abn(module):
    if isinstance(module, ABN):
        module.weight = torch.nn.Parameter(torch.abs(module.weight) + module.eps)
    for l in module.children():
        patch_abn(l)
# test it
abn = ABN(100, affine=True)
ipabn = InPlaceABN(100, affine=True)
ipabn.weight = torch.nn.Parameter(-torch.ones(100))
abn.weight = ipabn.weight
patch_abn(abn)
abn.cuda()
ipabn.cuda()
inp = torch.rand((10, 100, 3, 3)).cuda()
abn_out = abn(inp)
ipabn_out = ipabn(inp)
torch.abs(abn_out - ipabn_out).max()
```
for me it outputs something around `5e-07`

**Comment by LOOKCC** [comment]
@bonlime  I want to replace InplaceABN to ABN(or just BN + activation). Is there any way to do this?

**Comment by JiayuXu0** [comment]
> 

Why the outputs are not exactly the same
