### ISSUE TITLE
Problem with resnet50.pth.tar

### ISSUE THREAD

**Issue by manutom** [mapillary/inplace_abn#94]
while running the following command:
python3 test_vistas.py ../Model/wide_resnet38_deeplab_vistas.pth.tar ../input/ ../

Getting the following error:
['../Model/resnet50.pth.tar', '../input/', '../output/', '--world-size', '1', '--rank', '0']
--- Loading model from snapshot
Traceback (most recent call last):
  File "test_vistas_single_gpu.py", line 306, in <module>
    main()
  File "test_vistas_single_gpu.py", line 153, in main
    body, head, cls_state = load_snapshot(args.snapshot)
  File "test_vistas_single_gpu.py", line 212, in load_snapshot
    body.load_state_dict(data["state_dict"]["body"])
KeyError: 'body'

**Comment by rotabulo** [comment]
@manutom after the latest updates to the README some links got messed up. Can you retry downloading the vistas pre-trained model now?

**Comment by manutom** [comment]
@rotabulo 

It works now. thanks a lot for the super quick response
