### ISSUE TITLE
output_mode : probabilty

### ISSUE THREAD

**Issue by manutom** [mapillary/inplace_abn#95]
In semantic segmentation using test_vistas.py, what does the image output (other than gray scale labels) when the output mode is set to : _prob_

is it the per-pixel probability to be a segment boundary?

**Comment by rotabulo** [comment]
@manutom `prob` is just the pixel-wise probability of the most likely class. The correlation with boundaries is just a side-effect due to the confidence around boundaries being typically smaller.

**Comment by manutom** [comment]
Thanks a lot for the quick response
