### ISSUE TITLE
Some quastion about SyncBatchnorm

### ISSUE THREAD

**Issue by CS-Jackson** [mapillary/inplace_abn#96]
Hi, @rotabulo . Can I use nn.DataParallel(model) for Sync-Inplace_abn, supposed I have one machine with two GTX1080Ti.

**Comment by rotabulo** [comment]
@CS-Jackson the latest implementation of sync IABN works with _DistributedDataParallel_ also when you work on a single node. If you try to run it using `DataParallel`, it runs but without synchronizing.

**Comment by roominforest** [comment]
Hi,@rotabulo.I encounter a cuda error (out of memory) after several epochs of training and validation when I use Sync-Inplace_abn with DistributedDataParallel to train a 3d model. I wonder if Sync-Inplace_abn will make the master gpu memory consuming too much.

**Comment by rotabulo** [comment]
@roominforest the additional memory requirement of sync iABN is negligible, so I guess the issue comes from other parts of the code. We use it in every project and we never had issues so far.

**Comment by roominforest** [comment]
Thank you @rotabulo for your prompt response. I have found the crux of this issue.
